[Py] example missed import clauses
SeleniumHQ/seleniumhq.github.io pull request #1040
Opened 2022-06-09 09:09 UTC by unam3

### Description

Python code example missed import clauses.

### Motivation and Context

As a new user of the WebDriver I've spend almost an hour trying to figure out which modules should I import to run example. No links to documentation provided in the original pages which is unthinkable for project this big.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2022-06-09 09:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1040) <br/>All committers have signed the CLA.

2022-06-10 16:35 UTC, harsha509 requested changes

2022-06-10 16:35 UTC, harsha509 commented on website_and_docs/content/documentation/webdriver/getting_started/install_drivers.ja.md
> +
Can we remove extra spaces in here.
one space between imports and code would be better

```
from selenium.webdriver.chrome.service import Service
service = Service(executable_path="/path/to/chromedriver")

from selenium import webdriver
driver = webdriver.Chrome(service=service)
```

2022-06-13 09:47 UTC, unam3 commented on website_and_docs/content/documentation/webdriver/getting_started/install_drivers.ja.md
> +
doen

2022-06-13 16:54 UTC, harsha509 approved these changes
Thank you @unam3 !

2022-06-13 16:55 UTC, harsha509 commented
Congratulations on your first contribution to Selenium docs @unam3 🎉 🎉 🎉 !

2022-06-13 17:01 UTC, merged