add new blog post about BELLATRIX test automation framework
SeleniumHQ/seleniumhq.github.io pull request #1153
Opened 2022-08-30 11:45 UTC by angelovstanton

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description
I added a blog post regarding BELLATRIX test automation framework which we discussed with Diego Molina to be added as one of the frameworks from the Selenium Ecosystem

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2022-08-30 11:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1153) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1153) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1153) it.</sub>

2022-11-01 16:49 UTC, diemol commented
Apologies for the delay reviewing this, I will have a look tomorrow and merge it if everything is OK.

2022-11-02 07:10 UTC, angelovstanton commented
> Apologies for the delay reviewing this, I will have a look tomorrow and merge it if everything is OK.

No problem! I completely understand your busy schedule. As we discussed in Slack when we publish the blog post it will be great also to link the framework on the Ecosystem page where other frameworks are so that people can find it faster. Lastly when we talked we discussed all details. If there is anything related to the PR. Let's quickly resolve it in Slack, I will be online the whole working day! Thank you!

2022-11-09 16:33 UTC, diemol requested changes
👋 @angelovstanton, I left some comments and a remark at the end. Feel free to reach out in Slack so we can move forward.

2022-11-09 16:33 UTC, diemol commented on website_and_docs/content/blog/2022/bellatrix-test-automation-framework/index.md
> +title: "Selenium Ecosystem - BELLATRIX Test Automation Framework for C# and JAVA"
```suggestion
title: "BELLATRIX Test Automation Framework for C# and JAVA"
```

2022-11-09 16:33 UTC, diemol commented on website_and_docs/content/blog/2022/bellatrix-test-automation-framework/index.md
> +linkTitle: "Selenium Ecosystem - BELLATRIX Test Automation Framework for C# and JAVA"
```suggestion
linkTitle: "BELLATRIX Test Automation Framework for C# and JAVA"
```

2022-11-09 16:33 UTC, diemol commented on website_and_docs/content/blog/2022/bellatrix-test-automation-framework/index.md
> +date: 2022-09-01
```suggestion
date: 2022-11-10
```

2022-11-09 16:33 UTC, diemol commented on website_and_docs/content/blog/2022/bellatrix-test-automation-framework/index.md
> +One of these frameworks is BELLATRIX, developed and maintained by [Automate The Planet](https://bellatrix.solutions/about/) and invented by [Anton Angelov](https://www.linkedin.com/in/angelovstanton/
```suggestion
One of these frameworks is BELLATRIX, invented by [Anton Angelov](https://www.linkedin.com/in/angelovstanton/). It has two versions - C# and Java.
```

2022-11-09 16:33 UTC, diemol commented on website_and_docs/content/blog/2022/bellatrix-test-automation-framework/index.md
> +One of these frameworks is BELLATRIX, developed and maintained by [Automate The Planet](https://bellatrix.solutions/about/) and invented by [Anton Angelov](https://www.linkedin.com/in/angelovstanton/
I just want to avoid people commenting that we have a link to a company and thinking that we are promoting the company, whereas we want to promote the Open Source framework.

2022-11-09 16:33 UTC, diemol commented on website_and_docs/content/blog/2022/bellatrix-test-automation-framework/index.md
> +
While I can say that agree with this content, it is not the purpose of the blog to define a test framework. I'd prefer if we go more to the point and highlight BELLATRIX without loosing time in definitions.

If you wish, you can leave something along the lines of "A testing framework is an abstraction in which common code providing generic functionality (which can be selectively overridden) for testing different aspects of our applications- UI, API, security, performance and many other." 

And then connecting that with BELLATRIX.

2022-11-09 16:33 UTC, diemol commented on website_and_docs/content/blog/2022/bellatrix-test-automation-framework/index.md
> +API or application programming interface is a set of functions and procedures that allow the creation of applications which access the features or data of an operating system, application, or other s
I believe this could be summarized and added to the previous paragraph.

2022-11-09 16:33 UTC, diemol commented on website_and_docs/content/blog/2022/bellatrix-test-automation-framework/index.md
> +###Multiple Test Environments Configuration###
From this point on, it is hard for me to grasp why BELLATRIX is a good alternative. Wouldn't be better to show a simple "how to get started" so the reader gets interested about it, and after that mention the different features in a bullet list with a short description (like dynamic tests cases, email testing, etc...). 

When going too much into details, one misses the point of how to get started with the framework and what else could it offer me. I hope this makes sense to you.

2022-11-15 15:36 UTC, diemol requested changes
Looks good, a couple of suggestions and then we can merge tomorrow.

2022-11-15 15:36 UTC, diemol commented on website_and_docs/content/blog/2022/bellatrix-test-automation-framework/index.md
> +  Start on top of hundreds of best practice features and integrations.
```suggestion
  Customize and extend BELLATRIX, a cross-platform .NET 6 and JAVA test automation framework to perfectly fit your needs.
  Start on top of hundreds of best practices features and integrations.
```

2022-11-15 15:36 UTC, diemol commented on website_and_docs/content/blog/2022/bellatrix-test-automation-framework/index.md
> +date: 2022-11-10
```suggestion
date: 2022-11-16
```

2022-11-15 16:23 UTC, angelovstanton commented
> I committed directly from GitHub the two suggestions you made so I think we are good to go. Probably before publishing you need just to add the framework link to the Ecosystem page ( https://www.selenium.dev/ecosystem/) as we discussed before

2022-11-16 09:09 UTC, diemol approved these changes
Thank you, @angelovstanton!

2022-11-16 09:10 UTC, merged