JS/Kotlin adding examples and links
SeleniumHQ/seleniumhq.github.io pull request #1159
Opened 2022-09-07 15:46 UTC by hanceanic

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

Added JS examples and linked Kotlin examples from a previous PR

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2022-09-07 17:12 UTC, titusfortner commented
Can you add the JS references in wheel.en files as well? 
When we build the preview for Netlify it should grab from your branch to display properly

Thanks

2022-09-08 00:21 UTC, titusfortner commented
Oh shoot, I thought @diemol had dialed this one in. No matter, I pulled it locally to review.

2022-09-08 00:27 UTC, titusfortner requested changes
Thanks for this work!

The tests should work with the values that the rest of the languages are using, please update to those.

2022-09-08 00:27 UTC, titusfortner commented on examples/javascript/test/actionsApi/wheelTest.spec.js
> +        .scroll(0, 0, 0, 300, iframe)
match the other examples; use 200

2022-09-08 00:27 UTC, titusfortner commented on examples/javascript/test/actionsApi/wheelTest.spec.js
> +        .scroll(0, -30, 0, 300, footer)
should be 0, -50, 0, 200 to match other examples

2022-09-08 00:27 UTC, titusfortner commented on examples/javascript/test/actionsApi/wheelTest.spec.js
> +        .scroll(10, 10, 0, 5000)
10, 10, 0, 200

2022-09-08 11:13 UTC, harsha509 requested changes

2022-09-08 11:13 UTC, harsha509 commented on examples/javascript/test/actionsApi/wheelTest.spec.js
> +    after(() => driver.quit())
after(async() => await driver.quit())

2022-09-08 14:03 UTC, titusfortner approved these changes

2022-09-08 15:21 UTC, harsha509 approved these changes

2022-09-08 15:22 UTC, harsha509 approved these changes

2022-09-08 15:23 UTC, harsha509 commented
Thank you @hanceanic !

2022-09-08 15:23 UTC, merged