Update virtual_authenticator.zh-cn.md
SeleniumHQ/seleniumhq.github.io pull request #1193
Opened 2022-10-13 03:28 UTC by iambocai

Add  chinese translation of page <Virtual Authenticator>

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2022-10-13 03:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1193) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1193) it.</sub>

2022-10-13 14:18 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/interactions/virtual_authenticator.zh-cn.md
> +使用给定的所需凭据 [参数] (https://w3c.github.io/webauthn/#sctn-automation-add-credential) 创建一个永久凭据。
Additional space?

2022-10-13 14:26 UTC, alaahong requested changes, later dismissed
Can you take a look on the comment part?

2022-10-13 14:26 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/interactions/virtual_authenticator.zh-cn.md
> +使用给定的所需凭据 [参数] (https://w3c.github.io/webauthn/#sctn-automation-add-credential) 创建一个永久凭据。
Seems missed the original highlight word

2022-10-13 14:26 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/interactions/virtual_authenticator.zh-cn.md
> +使用给定的所需凭据 [参数] (https://w3c.github.io/webauthn/#sctn-automation-add-credential) 创建一个临时凭据。
Is that a parameter?

2022-10-13 14:28 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/interactions/virtual_authenticator.zh-cn.md
> +{{< /tabpane >}}
Additional change?

2022-11-01 16:45 UTC, diemol commented
@alaahong do you think you can make the requested changes so we merge these changes?

2022-11-03 14:34 UTC, alaahong commented
> @alaahong do you think you can make the requested changes so we merge these changes?

Sure, just commit. A bit confused on the resident credential, just treat as fixed/persisted credential.

2022-11-03 15:36 UTC, diemol approved these changes
Thank you, @alaahong!

2022-11-03 15:37 UTC, merged