Update install_drivers.zh-cn.md
SeleniumHQ/seleniumhq.github.io pull request #1238
Opened 2022-11-18 07:20 UTC by jasonren0403

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description
translate remaining EN content on install drivers page and change wording that may cause conflict

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2022-11-20 06:02 UTC, alaahong commented
Hi，
Thanks for your picking up the translation. It's a good start.
But can you do not change as below? Is there any necessary to replace all lines as yours even without revised?


![image](https://user-images.githubusercontent.com/3264250/202888131-ead9b20f-6a2f-4517-99e1-6a86943be06e.png)

2022-11-20 06:08 UTC, alaahong requested changes
Please do your changes based on existing content. You should keep compatibility if there was not exactly improvement on the translation. And meanwhile, you often merge several lines into one line as a long format (actually no change in rendered HTML) , even we mentioned you the contribution RULE. 

Otherwise, anyone also need change yours by any small point.

2022-11-20 06:24 UTC, jasonren0403 commented on website_and_docs/content/documentation/webdriver/getting_started/install_drivers.zh-cn.md
> +WebDriver尽量使用浏览器内置的自动化支持来驱动浏览器.
```suggestion
WebDriver尽量使用浏览器内置的自动化支持
来驱动浏览器.
```

2022-11-20 06:24 UTC, jasonren0403 commented on website_and_docs/content/documentation/webdriver/getting_started/install_drivers.zh-cn.md
> +由于除Internet Explorer之外的所有驱动程序实现都是由浏览器供应商自己提供的,
```suggestion
由于除Internet Explorer之外的所有驱动程序实现
都是由浏览器供应商自己提供的, 
```

2022-11-20 06:24 UTC, jasonren0403 commented on website_and_docs/content/documentation/webdriver/getting_started/install_drivers.zh-cn.md
> +在我们的[驱动程序配置]({{< ref "/documentation/webdriver/drivers/" >}}) 文档中，
```suggestion
在我们的[驱动程序配置]({{< ref "/documentation/webdriver/drivers/" >}}) 文档中
```

2022-11-20 06:25 UTC, jasonren0403 commented on website_and_docs/content/documentation/webdriver/getting_started/install_drivers.zh-cn.md
> +在代码中指定位置本身的优点是不需要指出系统上的环境变量,
```suggestion
在代码中指定位置本身的优点是
不需要指出系统上的环境变量, 
```

2022-11-20 16:36 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/getting_started/install_drivers.zh-cn.md
> +阅读有关 [Selenium Manager](/blog/2022/introducing-selenium-manager/) 的文章。
more at the blog announcement？

2022-11-21 01:37 UTC, jasonren0403 commented on website_and_docs/content/documentation/webdriver/getting_started/install_drivers.zh-cn.md
> +阅读有关 [Selenium Manager](/blog/2022/introducing-selenium-manager/) 的文章。
```suggestion
在这篇[公告](/blog/2022/introducing-selenium-manager/)中了解更多有关 Selenium Manager 的信息。
```

2022-11-21 12:25 UTC, alaahong approved these changes

2022-11-21 12:30 UTC, alaahong commented
Thanks you @jasonren0403 !

2022-11-21 12:30 UTC, merged