Update example section for keeping browser open
SeleniumHQ/seleniumhq.github.io pull request #1286
Opened 2023-01-18 13:06 UTC by Omjoa001

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ x ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2023-01-18 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1286) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1286) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1286) it.</sub>

2023-01-18 15:03 UTC, titusfortner commented
Nice, thanks! Would you like to also add the reference to this code on the browser/chrome.md page? Let us know if we can help.

2023-01-19 13:55 UTC, harsha509 commented
Hi @Omjoa001 ,

Hope you're doing great!

Did you got a chance to look into above comments ?

Thanks,
Sri

2023-01-20 13:42 UTC, harsha509 requested changes

2023-01-20 13:42 UTC, harsha509 commented on examples/python/tests/browsers/test_chrome.py
> +    chrome_options = Options()
chrome_options = ChromeOptions()

2023-01-25 06:31 UTC, harsha509 commented
HI @Omjoa001,

Thank you for the PR!

As the PR went stale, I have updated the changes with commit e544b2bfebb1752688adbbb4c8c5c2087b815e55 and 603367ec5fbbf89fa58b2a9bf69b4b69a9178f8b !

Thanks,
Sri Harsha

2023-01-25 06:31 UTC, closed without merging