Update chrome.zh-cn.md
SeleniumHQ/seleniumhq.github.io pull request #1309
Opened 2023-02-17 03:00 UTC by dk3817521

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

   Update chrome.zh-cn.md
### Motivation and Context

    Add some chineses translate
### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2023-02-17 03:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1309) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1309) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1309) it.</sub>

2023-02-17 14:33 UTC, alaahong requested changes
Alomst looks good, just comment on two special places...

2023-02-17 14:33 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
> +添加一个拓展程序到选项中:
Actully, it called "扩展程序" as common transalation..
https://support.google.com/chrome_webstore/answer/2664769?hl=zh-Hans

2023-02-17 14:33 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
> +添加一个布尔值到选项中:
Where is the boolean?

2023-02-20 08:07 UTC, dk3817521 commented on website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
> +添加一个布尔值到选项中:
Well..  i try to understand the original english text and the use case below:

English text:
 `Ad a binary to options:`

seems like the `detach` parameter accept `0 | 1` 

Use case:
`  let driver = await env
        .builder().setChromeOptions(options.detachDriver(true)).build();`

It seems like the `detach` parameter accept `true | false`. So here is the boolean.. 

Seems like the english text  doesn't match the use case very well
So i changed the `binary` to `boolean` to match the use case
Let me know if this isn't appropriate or if I'm misunderstand

2023-02-20 08:12 UTC, dk3817521 commented on website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
> +添加一个拓展程序到选项中:
> Actully, it called "扩展程序" as common transalation.. https://support.google.com/chrome_webstore/answer/2664769?hl=zh-Hans

Ok, got it !

2023-02-21 14:15 UTC, alaahong approved these changes
Many thanks, looks good~

2023-02-21 14:15 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
> +添加一个布尔值到选项中:
I see, seems you are right, this is confusing by original English wording. Looks good, thanks

2023-02-21 14:20 UTC, harsha509 commented
Thank you for the review @alaahong !

2023-02-21 14:20 UTC, merged

2023-02-21 14:22 UTC, harsha509 commented
Congratulations on your first contribution to Selenium-docs @dk3817521  :tada: 🎉 🎉 🎉