Task Keep browser open example added
SeleniumHQ/seleniumhq.github.io pull request #1327
Opened 2023-03-02 11:53 UTC by ankitkumar734ac

Example added.
Setting the detach parameter to true will keep the browser open after the driver process has been quit.

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2023-03-02 11:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1327) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1327) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1327) it.</sub>

2023-03-02 12:44 UTC, harsha509 approved these changes
Thank you @ankitkumar734ac !

2023-03-08 13:46 UTC, harsha509 commented
hi @ankitkumar734ac ,

Could you please sign CLA to get this merged ?

Thanks,
Sri

2023-03-08 13:54 UTC, ankitkumar734ac commented
> hi @ankitkumar734ac ,
> 
> Could you please sign CLA to get this merged ?
> 
> Thanks,
> Sri

Already Done but it still show pending

2023-03-08 13:59 UTC, diemol commented
Well, this user @kumarankit00792 still needs to sign it.

2023-03-08 15:40 UTC, titusfortner requested changes
Test method name is using Python convention not Java convention

2023-03-08 19:35 UTC, ankitkumar734ac commented
> ###

Done

2023-03-08 19:48 UTC, titusfortner commented on examples/java/src/test/java/dev/selenium/browsers/ChromeTest.java
> +    public void test_keep_browser_open() {
```suggestion
    public void keepBrowserOpen() {
```

2023-03-08 19:51 UTC, titusfortner commented
Would also be helpful to add the example to the docs themselves in the 4 different translation files:

https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/documentation/webdriver/browsers/chrome.en.md?plain=1#L121

(and thanks for helping us with this!)

2023-03-08 19:58 UTC, ankitkumar734ac reviewed
Method name changed as per suggestion

2023-03-08 20:01 UTC, ankitkumar734ac commented
> Would also be helpful to add the example to the docs themselves in the 4 different translation files:
> 
> https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/documentation/webdriver/browsers/chrome.en.md?plain=1#L121
> 
> (and thanks for helping us with this!)

Ok will try

2023-03-08 20:41 UTC, ankitkumar734ac commented
Example added in the docs for 4 different translation files

2023-03-10 06:17 UTC, harsha509 commented
Looks good to me!

Thank you @titusfortner for the in-detail review.

2023-03-10 06:17 UTC, harsha509 approved these changes

2023-03-10 06:52 UTC, merged