Changelocatorandinfo
SeleniumHQ/seleniumhq.github.io pull request #1337
Opened 2023-03-13 12:15 UTC by pallavigitwork

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

changed the locator and information document
### Description

modified js code
in both documents
### Motivation and Context

code got deleted. fixed a vaiable name
### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2023-03-20 16:32 UTC, harsha509 requested changes
Hi @pallavigitwork ,

Thank you for the PR. PR looks good to me to get started, but could you please revert the files `hugo.toml, package.json and package-lock.json`.

2023-03-20 16:32 UTC, harsha509 commented on website_and_docs/hugo.toml
> +ignoreErrors = ["error-remote-getjson"]
hi @pallavigitwork ,

This should be commented out.

2023-03-20 16:32 UTC, harsha509 commented on website_and_docs/package-lock.json
> +      "dev": true
Strange,

How come all packages are added with `dev:true` and am not sure hugo packages are updated!

2024-02-19 09:38 UTC, diemol commented
@pallavigitwork is this PR still valid?

2024-02-19 12:02 UTC, pallavigitwork commented
i will check and update you by this week.

2024-09-27 12:09 UTC, closed without merging