Update testing_types.en.md
SeleniumHQ/seleniumhq.github.io pull request #1506
Opened 2023-10-22 07:11 UTC by SripriyaPKulkarni

Updated the page with integration and system testing details.

2023-10-22 07:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1506) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1506) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1506) it.</sub>

2023-10-24 01:52 UTC, harsha509 requested changes
Hi @SripriyaPKulkarni ,

Thank you for the PR!

Could you please add similar changes in translated pages that are other than in English? (.pt-br.md, .zh-cn.md, .ja.md)

Thanks,
Sri

2023-10-24 04:32 UTC, SripriyaPKulkarni commented
Hi @harsha509 ,

I have updated the other three pages with respective languages.
https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1507

https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1508

https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1509
Please review.

Thanks,
Priya

2023-10-28 14:28 UTC, harsha509 approved these changes
Thank you @SripriyaPKulkarni !

2023-10-28 14:36 UTC, merged