Update testing_types.zh-cn.md in Chinese language
SeleniumHQ/seleniumhq.github.io pull request #1507
Opened 2023-10-24 04:23 UTC by SripriyaPKulkarni

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2023-10-28 14:33 UTC, harsha509 requested changes

2023-10-28 14:33 UTC, harsha509 commented on website_and_docs/content/documentation/test_practices/testing_types.zh-cn.md
> +jíchéng cèshì yànzhèng xìtǒng de bùtóng zǔjiàn huò mókuài zhī jiān de jiāohù. Jǐ gè mókuài yīqǐ cèshì. Jíchéng cèshì de mùdì shì quèbǎo suǒyǒu mókuài àn yùqí jíchéng bìng xiétóng gōngzuò. Zìdònghuà j
Hi @SripriyaPKulkarni,

You can set the text in English, translations will be done later for all other pages.

Can you replace this text with English, also I don't recognize this language as zh-cn

2025-03-24 13:12 UTC, alaahong commented on website_and_docs/content/documentation/test_practices/testing_types.zh-cn.md
> +jíchéng cèshì yànzhèng xìtǒng de bùtóng zǔjiàn huò mókuài zhī jiān de jiāohù. Jǐ gè mókuài yīqǐ cèshì. Jíchéng cèshì de mùdì shì quèbǎo suǒyǒu mókuài àn yùqí jíchéng bìng xiétóng gōngzuò. Zìdònghuà j
This is not the Chinese word, it's the Chinese Phonetic Alphabet， something  just like international Phonetic Alphabet for English. 
![2FA58723](https://github.com/user-attachments/assets/47fe37c5-f9f1-4365-94cb-8e87f89b01f8)

You can just follow harsha's comment to leave this for Chinese guys~

2025-06-18 13:09 UTC, diemol commented
Closing as this went stale.

2025-06-18 13:09 UTC, closed without merging