# feat : Add Portuguese translation in webdriver/support_features/expected_conditions
SeleniumHQ/seleniumhq.github.io pull request #1514
Opened 2023-10-25 14:19 UTC by sombo20

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2023-10-25 14:23 UTC, sombo20 commented
@luisfcorreia

2023-10-25 14:24 UTC, diemol commented
There is no need to tag people. We all get an email notification and we will review when time permits.

2023-10-25 14:25 UTC, sombo20 commented
@diemol  right!

2023-10-25 15:07 UTC, luisfcorreia commented
For future commits, please commit one file at the time, this takes longer to review.

2023-10-25 15:31 UTC, sombo20 commented
@luisfcorreia  I commit this file expected_conditions

2024-11-15 22:27 UTC, A1exKH requested changes
@sombo20 please, resolve conflicts for this PR.

2024-12-06 21:38 UTC, A1exKH approved these changes
LGTM.

2025-06-18 13:11 UTC, diemol commented
This went stale, closing.

2025-06-18 13:11 UTC, closed without merging