Update test_waits.py  add example test_explicity_expected_conditions
SeleniumHQ/seleniumhq.github.io pull request #1531
Opened 2023-11-17 06:28 UTC by snowlts

add testcase  test_explicity_expected_conditions for /examples/python/tests/waits
/test_waits.py 

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

add a python example for explicity_wait using expected_conditions;

### Motivation and Context

I found that there is no example for explicity_wait using expected_conditions.
so I add it, maybe it will be useful for someone who want to know how to use it

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2023-11-17 06:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1531) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1531) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1531) it.</sub>

2023-11-22 19:06 UTC, titusfortner requested changes
I'm biased. I don't think anyone should ever use the expected conditions classes when they can use lambdas.

So my preferences is for examples of expected conditions to go into the support section not the waits section.

Regardless, by adding an import at the top, the line references to this file will all need to be changed.

2024-11-07 22:44 UTC, A1exKH requested changes
@snowlts please check and address this comment, please:
https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1531#pullrequestreview-1745188247

2025-06-18 13:13 UTC, diemol commented
This went stale, closing.

2025-06-18 13:13 UTC, closed without merging