Update windows.en.md
SeleniumHQ/seleniumhq.github.io pull request #1535
Opened 2023-11-28 21:15 UTC by ronPy

fixed sample code to open a new window or tab using ruby

### Description
current sample code doesn't work, with this change user will be pointed to the right direction on how to open a new window or tab using ruby

### Motivation and Context
I was trying to achieve this and following the sample code didn't work, after looking at other languages I figured it out, maybe some people won't do that I will think the feature is just not working in ruby

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2023-11-28 21:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1535) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1535) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1535) it.</sub>

2023-11-29 03:12 UTC, titusfortner commented
Good catch, we changed the implementation of this and didn't update the documentation.
Can you update these lines in all 4 of the translation files?

(or if you are interested in being especially helpful write the code here so we can link to it in the docs? https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/ruby/spec/interactions/windows_spec.rb)

2023-11-29 03:49 UTC, titusfortner commented
@ronPy please sign the CLA. Thanks.

2023-11-29 07:31 UTC, diemol requested changes

2023-11-29 07:31 UTC, diemol commented on website_and_docs/content/documentation/webdriver/interactions/windows.ja.md
> +    driver.switch_to.new_window(:tab)
Please reference the `gh-codeblock` here as well.

2023-11-29 07:31 UTC, diemol commented on website_and_docs/content/documentation/webdriver/interactions/windows.ja.md
> +    driver.switch_to.new_window(:window)
Please reference the `gh-codeblock` here as well.

2023-11-29 07:31 UTC, diemol commented on website_and_docs/content/documentation/webdriver/interactions/windows.pt-br.md
> +    driver.switch_to.new_window(:tab)
Please reference the `gh-codeblock` here as well.

2023-11-29 07:31 UTC, diemol commented on website_and_docs/content/documentation/webdriver/interactions/windows.pt-br.md
> +    driver.switch_to.new_window(:window)
Please reference the `gh-codeblock` here as well.

2023-11-29 07:31 UTC, diemol commented on website_and_docs/content/documentation/webdriver/interactions/windows.zh-cn.md
> +    driver.switch_to.new_window(:tab)
Please reference the `gh-codeblock` here as well.

2023-11-29 07:31 UTC, diemol commented on website_and_docs/content/documentation/webdriver/interactions/windows.zh-cn.md
> +    driver.switch_to.new_window(:window)
Please reference the `gh-codeblock` here as well.

2023-11-29 14:35 UTC, titusfortner requested changes
Thank you so much for taking the extra step here!

A couple updates specific to how Hugo/Docsy need things formatted.
Also, I don't think we need to include any of the navigation things? Just the command to create the window/tab (and the assertion in the specs so when we run it in the CI we know it is working.

2023-11-29 14:35 UTC, titusfortner commented on website_and_docs/content/documentation/webdriver/interactions/windows.en.md
>    {{< tab header="Ruby" >}}
This keeps Hugo from trying to parse all of this as Ruby code.
```suggestion
  {{% tab header="Ruby" text=true %}}
```

2023-11-29 14:35 UTC, titusfortner commented on website_and_docs/content/documentation/webdriver/interactions/windows.en.md
>    {{< /tab >}}
Need to open and close the tab with `%` to support markdown instead of just text
```suggestion
  {{% /tab %}}
```

2023-11-29 14:35 UTC, titusfortner commented on website_and_docs/content/documentation/webdriver/interactions/windows.en.md
>      # Opens a new tab and switches to new tab
This doesn't have to be a comment when using markdown
```suggestion
    Opens a new tab and switches to new tab
```

2023-11-29 14:35 UTC, titusfortner commented on website_and_docs/content/documentation/webdriver/interactions/windows.en.md
>      # Opens a new window and switches to new window
This doesn't have to be a comment when using markdown
```suggestion
    Opens a new window and switches to new window
```

2023-12-05 09:14 UTC, diemol approved these changes
Thank you, @ronPy!

2023-12-05 09:28 UTC, merged