[dotnet] Adjust logging examples to use File Handler
SeleniumHQ/seleniumhq.github.io pull request #1542
Opened 2023-12-08 21:19 UTC by nvborisenko

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2023-12-11 21:37 UTC, titusfortner requested changes
When we update the example files, we also need to update the line references in these files (all translations): https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/documentation/webdriver/drivers/remote_webdriver.en.md?plain=1

2023-12-12 14:26 UTC, titusfortner commented
Looks like each of the runners have a different default version of Chrome, I've set it to use Stable by default.

2023-12-13 19:21 UTC, titusfortner requested changes
Looks like you added a line here - https://github.com/SeleniumHQ/seleniumhq.github.io/blob/702edf5f619cf48ed31c02d621032b1c1fcef095/examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L63

which threw everything off again

2023-12-13 19:21 UTC, titusfortner commented on website_and_docs/content/documentation/webdriver/drivers/remote_webdriver.en.md
> +{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L59-L63" >}}
```suggestion
{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L59-L62" >}}
```
Same for others

2023-12-13 19:21 UTC, titusfortner commented on website_and_docs/content/documentation/webdriver/drivers/remote_webdriver.en.md
> +{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L78" >}}
```suggestion
{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L79" >}}
```

2023-12-13 19:21 UTC, titusfortner commented on website_and_docs/content/documentation/webdriver/drivers/remote_webdriver.en.md
> +{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L83" >}}
```suggestion
{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L84" >}}
```

2023-12-13 19:21 UTC, titusfortner commented on website_and_docs/content/documentation/webdriver/drivers/remote_webdriver.en.md
> +{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L95-L99" >}}
```suggestion
{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L96-L100" >}}
```

2023-12-13 19:21 UTC, titusfortner commented on website_and_docs/content/documentation/webdriver/drivers/remote_webdriver.en.md
> +{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L71" >}}
```suggestion
{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L72" >}}
```

2023-12-13 20:53 UTC, nvborisenko commented on website_and_docs/content/documentation/webdriver/drivers/remote_webdriver.en.md
> +{{< gh-codeblock path="examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L59-L63" >}}
I did it the same as for java.

2023-12-13 23:02 UTC, titusfortner approved these changes

2023-12-13 23:02 UTC, merged