Translate English text of `Finders.zh-cn.md` page into Chinese
SeleniumHQ/seleniumhq.github.io pull request #1592
Opened 2024-02-28 14:51 UTC by geekmister

# Translate English text of `Finders.zh-cn.md` page into Chinese 

### Description

I just modify `Finders.zh-cn.md` to translate English text into Chinese.

### Motivation and Context

Help Chinese to reading the section. It solved the problem that part of chinese to read diffcaulty English.

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [x] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-02-28 14:58 UTC, geekmister commented
About the second option of `CheckList`, it's not done. Because of try and try build local enviroment with `hugo` is failed. But I just translate, then preview with `markdown`. So, I think no problems.

2024-03-03 15:46 UTC, alaahong requested changes
Thanks for your commit, can you kindly take a look on the comments?

2024-03-03 15:46 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/elements/locators.zh-cn.md
> +我们可以在一个网页中使用元素可用属性`NAME`来定位它。通常在网页中严肃`NAME`属性应该是唯一的。我们将使用`NAME`来识别`Newsletter`复选框。
What‘s the 严肃`NAME` ?

2024-03-03 15:46 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/elements/locators.zh-cn.md
> +我们可以在一个网页中使用元素可用属性`ID`来定位它。通常在网页中元素的`ID`属性应该是唯一的。我们将使用`ID`来识别`Last Name`字段。
Seems no need to involve additional  back quote， you can just leave the English keywords there and the back quote has special usage in markdown.

2024-03-03 15:47 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/elements/finders.zh-cn.md
> +title: "查找网页元素"
where is the web page ?

2024-03-03 15:50 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/elements/finders.zh-cn.md
> +获得元素的引用是使用`Selenium`最重要且最基本的应用。`Selenium`提供内置定位器策略用来唯一地标识一个元素。在非常复杂的场景中有很多种方式使用定位器。为了表达这篇文档的目的，让我们探讨下这段`HTML`片段。
Please read this if you want to contribute more , it's not recommended for such a long line

https://www.selenium.dev/documentation/about/contributing/#step-4-commit

2024-03-03 15:53 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/elements/finders.zh-cn.md
> +当查找元素方法被驱动实例调用时，它会返回使用提供的定位器在文档中匹配到的第一个元素的引用。这个值可以存储和以后的元素操作中使用。在我们的`HTML`示例上，有两个元素的样式类名是`tomatoes`，所以这个方法会返回`vegetables`列表中的元素。
What your opinion on "这个值可以存储和以后的元素操作中使用。" ?

2024-03-03 15:56 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/elements/finders.zh-cn.md
> +而不是在整个文档中查找一个唯一的定位器，在另一个已经定位元素范围内缩小查找范围是常常有用的。在示例上有两个元素使用了`tomatoes`的样式类名，获得第二个元素的引用就有些困难了。
In Chinese， we won't use “而不是” as the start of one paragraph, no any context there.

2024-03-03 16:04 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/elements/finders.zh-cn.md
> +有几个用例需要获得匹配定位器的所有元素的引用，而不只是获得第一个匹配到元素。查找多个元素的方法会返回一个元素引用集合。如果没有匹配，这返回一个空的列表。在这个用例中，将返回所有`fruits`和`vegetable`的列表项元素引用的集合。
Sounds odd "而不只是获得第一个匹配到元素"

2024-03-03 16:07 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/elements/finders.zh-cn.md
> +常常你想从获得的元素集合中获得指定的元素，意思是你需要遍历集合和识别出你想要的那个。
sounds odd...

2024-03-03 16:08 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/elements/finders.zh-cn.md
> +它用于在父元素上下文内查找匹配子元素的列表，实现这个，父元素使用`findElements`访问子元素。
you can try better on "To achieve this, the parent WebElement is chained with 'findElements' to access child elements"

2024-03-03 16:10 UTC, alaahong commented on website_and_docs/content/documentation/webdriver/elements/locators.zh-cn.md
> +定位器是一种在页面上识别元素的方法。定位器是[查找元素]({{< ref "finders.md" >}}) 方法的参数。
why remove the line breaks ...

2024-03-03 16:20 UTC, alaahong commented
Hi, some tips.

1. You should review the contribution guide https://www.selenium.dev/documentation/about/contributing/#step-4-commit
2. No need to add additional punctuation， it will confuse other translators when they working later
3. No need to change all as your styles even there are existing translated parts and no big gap in translated version
4. Just read again and again before commit, some parts are hard to read and understand.

2024-05-27 07:04 UTC, closed without merging