Fix broken link that stops initialization and add one ruby example
SeleniumHQ/seleniumhq.github.io pull request #1613
Opened 2024-03-23 14:40 UTC by aguspe

### Description
This PR was to add missing ruby examples on the documentation, but when I was setting up I couldn't start the hugo server, so I just fixed the broken links instead

### Motivation and Context
I was going through the docs and I noticed that this URL https://www.selenium.dev/documentation/selenium_manager/(https://github.com/SeleniumHQ/selenium/actions/workflows/ci-rust.yml) which is present on this page: https://www.selenium.dev/documentation/selenium_manager/

Was throwing a 404 error, and it was the same error that I had when trying to initialize the Hugo server on my Mac

`Built in 4316 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/Users/apeque01/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.8.0/layouts/docs/single.html:2:3": execute of template failed: template: docs/single.html:2:3: executing "main" at <.Render>: error calling Render: failed to execute template _default/content.html: "/Users/apeque01/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.8.0/layouts/_default/content.html:10:4": execute of template failed: template: _default/content.html:10:4: executing "_default/content.html" at <.Content>: error calling Content: "/Users/apeque01/Desktop/seleniumhq.github.io/website_and_docs/content/documentation/selenium_manager.pt-br.md:1:1": execute of template failed: template: _default/_markup/render-link.html:1:14: executing "_default/_markup/render-link.html" at <urls.Parse>: error calling Parse: parse "(https://github.com/SeleniumHQ/selenium/actions/workflows/ci-rust.yml)": first path segment in URL cannot contain colon
`

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [X] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [X] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [X] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-03-25 13:47 UTC, aguspe commented
@titusfortner I checked your PR and fixed the same issue https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1612 that did not let me build

So once that your PR is merged I will update this branch, and just have the changes to the ruby docs

2024-03-26 16:10 UTC, diemol requested changes

2024-03-26 16:10 UTC, diemol commented on examples/ruby/spec/getting_started/first_script.rb
> +# ruby first_script.rb
You can add those comments [here](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/ruby/README.md). In a generic way, ideally.

2024-03-26 16:10 UTC, diemol commented on website_and_docs/content/documentation/webdriver/getting_started/first_script.en.md
> +{{< gh-codeblock path="examples/ruby/spec/getting_started/first_script.rb#L23" >}}
We don't want the instructions to be comments in the code. It could be a link directing to the README file.

2024-03-26 20:26 UTC, aguspe commented
Thank you for your review @diemol, let me know if there are more needed changes or anything else I should change

2024-03-27 14:51 UTC, diemol approved these changes
Thank you, @aguspe!

2024-03-31 22:52 UTC, diemol approved these changes
Thank you, @aguspe!

2024-03-31 22:52 UTC, merged