Expand options documentation test and examples for Ruby
SeleniumHQ/seleniumhq.github.io pull request #1679
Opened 2024-04-19 18:43 UTC by aguspe

### Description
This PR adds extra tests for the options in ruby and updates the documentation examples, besides that, it also moves the proxy example from the documentation file

### Motivation and Context
For new and experienced user to be able to fully understand all the options offered by Selenium is important to have up-to-date documentation with examples

### Types of changes
- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist
- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-04-19 18:44 UTC, aguspe commented
Hello @diemol one question about the documentation, does it make sense that the timeouts are under the options page and not on its page?

If it does, I can also update the timeouts example on this PR

<img width="1192" alt="Screenshot 2024-04-19 at 20 40 42" src="https://github.com/SeleniumHQ/seleniumhq.github.io/assets/33221555/b9754131-2987-4cf2-b371-e45433e48c4f">

2024-04-24 14:48 UTC, harsha509 requested changes

2024-04-24 14:48 UTC, harsha509 commented on examples/ruby/spec/drivers/options_spec.rb
> +      driver.get('https://www.google.com')
can we use https://www.selenium.dev/selenium/web/

2024-04-24 14:48 UTC, harsha509 commented on examples/ruby/spec/drivers/options_spec.rb
> +      driver.get('https://www.google.com')
can we use https://www.selenium.dev/selenium/web/ for all navigations etc.

2024-04-24 15:05 UTC, harsha509 commented
> Hello @diemol one question about the documentation, does it make sense that the timeouts are under the options page and not on its page?
> 
> If it does, I can also update the timeouts example on this PR
> 
> <img alt="Screenshot 2024-04-19 at 20 40 42" width="1192" src="https://private-user-images.githubusercontent.com/33221555/324081481-b9754131-2987-4cf2-b371-e45433e48c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzA2NzcsIm5iZiI6MTcxMzk3MDM3NywicGF0aCI6Ii8zMzIyMTU1NS8zMjQwODE0ODEtYjk3NTQxMzEtMjk4Ny00Y2YyLWIzNzEtZTQ1NDMzZTQ4YzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE0NTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MzY4NDZlZjc1OTI5NTFlYTZlMjhmZjE5OWRkZWUzMjRkNDYzMjk0Zjg1NTdiNTlmNTZiM2E0NzUyMzFiYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pdl_CzXM-JDfpwwT3UGo6x4S43RUarbfvMywPvo-NQ4">

Hi @aguspe,

The timeout mentioned refers to the W3C capability timeout in W3C WebDriver, see https://www.w3.org/TR/webdriver2/#capabilities

Also, It covers features like `ScriptTimeout`, `PageLoadTimeout`, and `ImplicitWaitTimeout`, as per the WebDriver documentation. see https://www.w3.org/TR/webdriver2/#timeouts

So, I believe it's correctly included in the driver options section.

Thanks,
Sri

2024-04-24 21:14 UTC, aguspe commented
> > Hello @diemol one question about the documentation, does it make sense that the timeouts are under the options page and not on its page?
> > If it does, I can also update the timeouts example on this PR
> > <img alt="Screenshot 2024-04-19 at 20 40 42" width="1192" src="https://private-user-images.githubusercontent.com/33221555/324081481-b9754131-2987-4cf2-b371-e45433e48c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzA2NzcsIm5iZiI6MTcxMzk3MDM3NywicGF0aCI6Ii8zMzIyMTU1NS8zMjQwODE0ODEtYjk3NTQxMzEtMjk4Ny00Y2YyLWIzNzEtZTQ1NDMzZTQ4YzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE0NTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MzY4NDZlZjc1OTI5NTFlYTZlMjhmZjE5OWRkZWUzMjRkNDYzMjk0Zjg1NTdiNTlmNTZiM2E0NzUyMzFiYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pdl_CzXM-JDfpwwT3UGo6x4S43RUarbfvMywPvo-NQ4">
> 
> Hi @aguspe,
> 
> The timeout mentioned refers to the W3C capability timeout in W3C WebDriver, see https://www.w3.org/TR/webdriver2/#capabilities
> 
> Also, It covers features like `ScriptTimeout`, `PageLoadTimeout`, and `ImplicitWaitTimeout`, as per the WebDriver documentation. see https://www.w3.org/TR/webdriver2/#timeouts
> 
> So, I believe it's correctly included in the driver options section.
> 
> Thanks, Sri

Thank you so much for the help I have updated this PR to cover the timeout examples :)

2024-04-25 12:30 UTC, harsha509 approved these changes

2024-04-25 12:32 UTC, aguspe commented
Hi @harsha509 before this gets merged I need to update some lines because I added a new let on the Rspec test so I'm missing some updates

2024-04-25 12:35 UTC, harsha509 commented
HI @aguspe ,

can you do it in a new PR if possible ? let me know

Thanks,
Sri

2024-04-25 13:15 UTC, aguspe commented
> HI @aguspe ,
> 
> can you do it in a new PR if possible ? let me know
> 
> Thanks, Sri

I just update it in a commit here and I fixed a documentation bug, I hope that's okey

2024-04-26 14:46 UTC, aguspe commented
Hello @harsha509 would it be possible to merge this PR? I will create a new PR to expand the selenium docs and correct an issue with the upgrade selenium ruby example but I keep merging trunk into this PR because it gets out of sync :)

Thank you so much

2024-04-26 16:06 UTC, aguspe commented
This PR needs to be merged before #1695

2024-04-27 10:05 UTC, harsha509 approved these changes

2024-04-27 10:06 UTC, harsha509 commented
Thank you @aguspe !

2024-04-27 10:06 UTC, merged