Added content for ElementClickInterceptedException
SeleniumHQ/seleniumhq.github.io pull request #1707
Opened 2024-05-03 22:48 UTC by chamiz

Added content for ElementClickInterceptedException

### Description
Added a new guide to find causes of ElementClickInterceptedException and suggested some solutions.

### Motivation and Context
[🚀 Feature]: Expand Error Messages #1276
https://github.com/SeleniumHQ/seleniumhq.github.io/issues/1276

### Types of changes

- [ X] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ X] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ X] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-05-14 23:13 UTC, chamiz commented
@diemol Can you please review this? So I can add more content for the error documentation.

2024-05-15 02:57 UTC, diemol commented
I think it looks good, but the content is missing from the other languages pages.

2024-12-04 20:45 UTC, A1exKH requested changes
@chamiz PR LGTM.
Please, resolve conflicts for that PR.

2025-08-16 19:40 UTC, diemol commented
Unfortunately, another user sent a PR that covered all 4 language files. Closing this PR.

2025-08-16 19:40 UTC, closed without merging