Start adding special features examples
SeleniumHQ/seleniumhq.github.io pull request #1711
Opened 2024-05-07 16:03 UTC by aguspe

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-05-10 06:41 UTC, harsha509 approved these changes
Thank you @aguspe !

2024-05-10 06:43 UTC, harsha509 reviewed
HI @aguspe,

Can we just include code from L119-L122 Or L124?

2024-05-10 06:50 UTC, aguspe commented
> HI @aguspe,
> 
> Can we just include code from L119-L122 Or L124?

Hi @harsha509 thank you so much for the question, I think the best is still L119-L124 because in the current implementation if people try just to use @driver.cast_sinks it will actually not work

I made a question regarding this on the slack channel to see how much we needed to expand the example for the users, here is the message: https://seleniumhq.slack.com/archives/C0K0BK8MQ/p1715280896233389

2024-05-10 06:59 UTC, harsha509 commented
> > HI @aguspe,
> > Can we just include code from L119-L122 Or L124?
> 
> Hi @harsha509 thank you so much for the question, I think the best is still L119-L124 because in the current implementation if people try just to use @driver.cast_sinks it will actually not work
> 
> I made a question regarding this on the slack channel to see how much we needed to expand the example for the users, here is the message: https://seleniumhq.slack.com/archives/C0K0BK8MQ/p1715280896233389

L119-L124 looks fine to me...

2024-05-10 07:05 UTC, aguspe commented
> > > HI @aguspe,
> > > Can we just include code from L119-L122 Or L124?
> > 
> > 
> > Hi @harsha509 thank you so much for the question, I think the best is still L119-L124 because in the current implementation if people try just to use @driver.cast_sinks it will actually not work
> > I made a question regarding this on the slack channel to see how much we needed to expand the example for the users, here is the message: https://seleniumhq.slack.com/archives/C0K0BK8MQ/p1715280896233389
> 
> L119-L124 looks fine to me...

Perfect thank you so much @harsha509, let me know if there are other questions

2024-05-11 05:19 UTC, harsha509 requested changes

2024-05-11 05:19 UTC, harsha509 commented on website_and_docs/content/documentation/webdriver/browsers/chrome.en.md
> +{{< gh-codeblock path="examples/ruby/spec/drivers/chrome_spec.rb#L118-L125" >}}
So can you change these ?

2024-05-11 07:29 UTC, aguspe commented on website_and_docs/content/documentation/webdriver/browsers/chrome.en.md
> +{{< gh-codeblock path="examples/ruby/spec/drivers/chrome_spec.rb#L118-L125" >}}
Hi @harsha509 is updated now, have a great weekend!

2024-05-11 07:51 UTC, harsha509 approved these changes

2024-05-11 15:00 UTC, merged