update example versions for 4.22
SeleniumHQ/seleniumhq.github.io pull request #1765
Opened 2024-06-20 22:04 UTC by titusfortner

### Description
Running tests
Blog Post in progress

### Motivation and Context
Selenium 4.22!

2024-06-24 14:52 UTC, p0deje commented on website_and_docs/content/blog/2024/selenium-4-22-released.md
> +  * Selenium has at least [2.6 active users](https://plausible.io/manager.selenium.dev) in the last 30 days. 200k more than last month!
2.6M!

2024-06-25 00:46 UTC, titusfortner commented on website_and_docs/content/blog/2024/selenium-4-22-released.md
> +  * Selenium has at least [2.6 active users](https://plausible.io/manager.selenium.dev) in the last 30 days. 200k more than last month!
I know, right?

2024-06-25 06:36 UTC, pujagani requested changes

2024-06-25 06:36 UTC, pujagani commented on website_and_docs/content/documentation/webdriver/bidirectional/webdriver_bidi/browsing_context.ja.md
Folks interested in BiDi (contributors and users) often ask for documentation and it is easy to point them to this section to start with. Our messaging is that Selenium supports projects that build opinionated APIs using Selenium APIs so we need documentation and code examples for both high-level API and low-level APIs.

2024-06-25 09:37 UTC, pujagani commented on website_and_docs/content/blog/2024/selenium-4-22-released.md
> +    * Video file name in Dynamic Grid can be seet with `se:videoName` capability.
nit "set"

2024-07-10 15:34 UTC, merged