Update first_script.en.md
SeleniumHQ/seleniumhq.github.io pull request #1780
Opened 2024-06-24 03:30 UTC by darrenqchen

In step 7 for Python, the code block is missing line 18 which creates the message variable. This way people that are following along the `"getting_started"` tutorial won't be as confused.

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-06-24 03:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1780) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1780) it.</sub>

2024-06-24 03:34 UTC, darrenqchen commented
Found this error since I was trying to do the tutorial myself for the first time.

2024-07-09 09:30 UTC, harsha509 requested changes
HI @darrenqchen ,

Thank you for the PR.

Your feedback is indeed beneficial in our efforts towards refining and enhancing our documentation.

To maintain consistency across all language versions, could you please replicate the changes you made on the main page to the other translated pages (pt-br, zh-cn, ja)? 

If you need any assistance or prefer me to implement the changes, kindly let me know.

Thanks,
Sri

2024-11-08 19:23 UTC, A1exKH approved these changes
LGTM.

2026-07-22 15:23 UTC, diemol commented
It seems this change was done in a different PR. I am sorry we did not get to yours earlier.

2026-07-22 15:23 UTC, closed without merging