Fixing consistency and English grammar
SeleniumHQ/seleniumhq.github.io pull request #1804
Opened 2024-07-09 12:01 UTC by Nisim761

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-07-10 12:59 UTC, Nisim761 commented
@harsha509 Can you please update what is missing?

2024-07-10 13:07 UTC, harsha509 requested changes
HI @Nisim761 ,
Thanks for your PR.

Could you also implement similar updates in other translated pages that are still in English?

For reference, you can use this commit: https://github.com/SeleniumHQ/seleniumhq.github.io/commit/fa62b405393ba396d9579fef35630489e6fea533

We have documentations that are maintained in 3 other languages:

https://www.selenium.dev/ja/documentation/webdriver/elements/locators/ https://www.selenium.dev/pt-br/documentation/webdriver/elements/locators/ https://www.selenium.dev/zh-cn/documentation/webdriver/elements/locators/

These need to be updated as well.

Thanks,
Sri

2024-11-04 21:14 UTC, A1exKH approved these changes
LGTM.

2025-08-14 20:28 UTC, closed without merging

2025-08-14 20:28 UTC, diemol commented
I will close this because the OP did not address the feedback.