Create chrome-browser-woes
SeleniumHQ/seleniumhq.github.io pull request #1853
Opened 2024-08-11 17:59 UTC by skyhirider

Creating this pull request based on feedback from https://github.com/SeleniumHQ/selenium/issues/14342

Feel free to make suggestions to the blog post.

2024-08-13 03:13 UTC, harsha509 requested changes
HI @skyhirider,

Thanks for the informative blog! 

However, it seems a bit incomplete and is missing titles and tags. Could you please update it with these details?

I’ve provided a sample below for reference, but feel free to rewrite it in your own style.
https://gist.github.com/harsha509/7850feaceeeead02af0ed47a8579dbc1

Thanks,
Sri

2024-08-13 03:13 UTC, harsha509 commented on website_and_docs/content/blog/2024/chrome-browser-woes
> +#Two Chrome browser woes that might affect you
```suggestion
title: 
linkTitle:
date: 
tags: ["chrome"]
categories: ["general"]
author: <name> <link to social profile handle>
description: 
---

#Two Chrome browser woes that might affect you
```

2024-08-13 16:07 UTC, skyhirider commented
@harsha509 thanks for the suggestion, updated the article. Let me know if more changes are needed.

2024-08-15 14:30 UTC, harsha509 requested changes, later dismissed

2024-08-15 14:30 UTC, harsha509 commented on website_and_docs/content/blog/2024/chrome-browser-woes
> +## Search engine selections creen
```suggestion
## Search engine selection screen
```

2024-08-15 14:30 UTC, harsha509 commented on website_and_docs/content/blog/2024/chrome-browser-woes
> +## Chrome wastes over 60MB of you bandwidth downloading language plugins
```suggestion
## Chrome wastes over 60MB of your bandwidth downloading language plugins
```

2024-08-18 10:15 UTC, skyhirider commented
Thanks for pointing out the typos, missed them when re-reading. Fixed.

2024-08-19 10:11 UTC, diemol approved these changes
Thank you, @skyhirider!

2024-08-19 10:12 UTC, merged