Updated python docs/examples for browsers section
SeleniumHQ/seleniumhq.github.io pull request #1854
Opened 2024-08-12 17:56 UTC by pmartinez1

Moved or added examples in python docs for browsers (for all missing examples)

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

Added and moved all relevant python code examples for the browsers section.

### Motivation and Context

It will allow python users to see examples of working code so they can more easily and efficiently work with selenium.

### Types of changes

- [ x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-08-12 17:56 UTC, pmartinez1 commented
Am still going to test locally with the github code blocks. Will close this comment when done.

2024-08-12 17:57 UTC, pmartinez1 commented on website_and_docs/content/documentation/webdriver/browsers/chrome.en.md
>  {{% tab header="Python" %}}
Am still going to test locally with the github code blocks. Will close this comment when done.

2024-08-20 15:25 UTC, pmartinez1 commented
Hi @harsha509,
Do you have any suggestion on how to test in Windows? I have a mac. 3 python examples tests failed. I believed I was able to resolve one of the failures (the error was pretty clear as to what was going on), but it would be best to fully confirm.

2024-08-20 22:29 UTC, pmartinez1 commented
Same failures, looks like I should not have passed in the second argument "True" in add_argument (https://github.com/SeleniumHQ/seleniumhq.github.io/blob/247ac2eea97e8d6031a357e84bb17f01c3175021/examples/python/tests/browsers/test_internet_explorer.py#L119). Quite possibly the other two are failing because they are trying to use the same instance of IE? Relevant: https://www.selenium.dev/documentation/ie_driver_server/. I'll look into this more and find a way of running it myself.

2024-08-21 00:36 UTC, pmartinez1 commented
> Same failures, looks like I should not have passed in the second argument "True" in add_argument (
> 
> https://github.com/SeleniumHQ/seleniumhq.github.io/blob/247ac2eea97e8d6031a357e84bb17f01c3175021/examples/python/tests/browsers/test_internet_explorer.py#L119
> ). Quite possibly the other two are failing because they are trying to use the same instance of IE? Relevant: https://www.selenium.dev/documentation/ie_driver_server/. I'll look into this more and find a way of running it myself.

Resolved the failure due to the "true" argument being passed in. The other failures are due to the use of the force_create_process_api value being set. According to the docs: "Windows Registry HKLM_CURRENT_USER\\Software\\Microsoft\\Internet Explorer\\Main path should contain key TabProcGrowth with 0 value."

I think the solution could be to have the test with force_create_process_api set to true to be skipped, as it could fail, if the value of the key above isn't set to 0. I will push that update, please let me know if it is not acceptable.

2024-08-21 03:49 UTC, pmartinez1 commented
> > Same failures, looks like I should not have passed in the second argument "True" in add_argument (
> > https://github.com/SeleniumHQ/seleniumhq.github.io/blob/247ac2eea97e8d6031a357e84bb17f01c3175021/examples/python/tests/browsers/test_internet_explorer.py#L119
> > 
> > ). Quite possibly the other two are failing because they are trying to use the same instance of IE? Relevant: https://www.selenium.dev/documentation/ie_driver_server/. I'll look into this more and find a way of running it myself.
> 
> Resolved the failure due to the "true" argument being passed in. The other failures are due to the use of the force_create_process_api value being set. According to the docs: "Windows Registry HKLM_CURRENT_USER\Software\Microsoft\Internet Explorer\Main path should contain key TabProcGrowth with 0 value."
> 
> I think the solution could be to have the test with force_create_process_api set to true to be skipped, as it could fail, if the value of the key above isn't set to 0. I will push that update, please let me know if it is not acceptable.

Updated and ready for review.

2024-08-24 23:33 UTC, pmartinez1 commented
Hi @harsha509 ,

The tests that were failing before, passed on the last run. The tests that failed, were not touched by me and they were timeouts. Could the checks be run again?

Thanks.

2024-09-06 18:14 UTC, pmartinez1 commented
Could I get a review please?

2024-09-06 18:16 UTC, harsha509 requested changes

2024-09-06 18:16 UTC, harsha509 commented on examples/python/tests/browsers/test_edge.py
> +    driver = webdriver.Chrome()
webdriver.Edge()

2024-09-09 20:04 UTC, pmartinez1 commented on examples/python/tests/browsers/test_edge.py
> +    driver = webdriver.Chrome()
Good catch! Updated.

2024-09-09 20:13 UTC, harsha509 approved these changes

2024-09-23 18:52 UTC, pmartinez1 commented
Looks like this has been failing its checks consistently. Updating to a draft, so I can figure out the issue. I'll update this PR once I have seen them all pass consistently.

2024-11-07 22:01 UTC, VietND96 commented
Could you please resolve conflict in this PR?

2024-12-12 22:42 UTC, closed without merging

2024-12-12 22:42 UTC, pmartinez1 commented
Closing this PR as someone else implemented the same stuff already.