Update python locators docs
SeleniumHQ/seleniumhq.github.io pull request #1903
Opened 2024-08-27 18:26 UTC by pmartinez1

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description
This PR moves the code to the test_locators.py file in the python/tests directory. 

### Motivation and Context

Helps the code be more organized, instead of having stand alone code that has not been tested.

### Types of changes

- [x ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-09-06 18:13 UTC, pmartinez1 commented
Could I get a review please?

2024-09-18 14:51 UTC, shbenzer requested changes
pytest import is unnecessary, pytest will not run a function if it is not prefixed by test unless explicitly called in a test function. Line #70 can be removed as well

2024-09-21 00:51 UTC, pmartinez1 commented
> Thank you for the contribution @pmartinez1 ! A few changes must be made before it can be properly reviewed:
> 
> pytest import is unnecessary, pytest will not run a function if it is not prefixed by test unless explicitly called in a test function. Line 70 can be removed as well

Thanks for pointing that out. I've updated the PR.

2024-09-24 17:07 UTC, shbenzer commented
Sorry about that, honestly forgot the relative locator section was included in this pr. I only did a cursory look through this commit's changes and commented when I saw you added an import for pytest.

Could you expand the relative locator section to have an individual test for each relative locator (above, below, rightof, leftof, and near)? 

Once that's done I'll test it locally

2024-09-24 17:58 UTC, pmartinez1 commented
> Sorry about that, honestly forgot the relative locator section was included in this pr. I only did a cursory look through this commit's changes and commented when I saw you added an import for pytest.
> 
> Could you expand the relative locator section to have an individual test for each relative locator (above, below, rightof, leftof, and near)?
> 
> Once that's done I'll test it locally

No problem. And yes, will split them up.

2024-09-24 20:21 UTC, pmartinez1 commented
> > Sorry about that, honestly forgot the relative locator section was included in this pr. I only did a cursory look through this commit's changes and commented when I saw you added an import for pytest.
> > Could you expand the relative locator section to have an individual test for each relative locator (above, below, rightof, leftof, and near)?
> > Once that's done I'll test it locally
> 
> No problem. And yes, will split them up.

I ended updating them a bit more. Originally, I had created the test not to run, but follow along with the static image that is present, but I think your approach is better. I borrowed a little from your PR (for the sake of expediency) and now the tests are ready to be run.

2024-09-24 20:45 UTC, shbenzer commented
Use what's available, I don't mind. I'll pull the branch for test

2024-09-24 21:02 UTC, shbenzer commented
Tested changes locally and looks good. The goal is to move all the code examples to executable files in the repo, so eventually this whole section on relative locators will eventually be refactored to no longer refer to that image. 

What do you think? @harsha509

2024-10-03 20:45 UTC, pmartinez1 commented
Hi @harsha509,

Would you be able to give this a review? @shbenzer has already given it one pass.

Thank you.

2024-10-04 03:31 UTC, harsha509 approved these changes, later dismissed
Thank you @pmartinez1 !

2024-10-04 19:00 UTC, pmartinez1 commented
Wow. Again tests are failing on my PR :(

For some reason, the "test_find_by_link_text" test is failing on Windows only, but seems to be deterministic. Does anyone have a Windows machine they can test on? Any ideas? I can't think of a reason why it fails there or at all. The test is simply going to the [Selenium](https://www.selenium.dev/) and looking for "Documentation". It passes in every other environment and a similar test, "test_find_by_partial_link_text" passes with no issue everywhere. 

I could add waits to see if it is a timing/loading issue?

I haven't gotten around to finding an option for testing Windows yet, but it is on my list.
<img width="1335" alt="Screenshot 2024-10-04 at 11 40 42 AM" src="https://github.com/user-attachments/assets/55d3e003-54a7-4eb8-ab96-f4b6c1a06e73">

2024-10-25 19:36 UTC, A1exKH requested changes
@pmartinez1 Code in your PR LGTM.
Please investigate and fix failed tests.

2024-11-25 23:02 UTC, pmartinez1 commented
> @pmartinez1 Code in your PR LGTM. Please investigate and fix failed tests.

Sorry for the super long delay. I am back and looking into this today. Will update as soon as I figure out the cause.

2024-12-12 22:29 UTC, pmartinez1 commented
> @pmartinez1 Code in your PR LGTM. Please investigate and fix failed tests.

I believe I have fixed the failures in the tests. The only tests I see failing now are the same macOS failures I am seeing on all of the most recent "run python" workflows. I think this is good for another review/approval. Thank you

2025-05-03 14:36 UTC, shbenzer commented
Once the conflicts are resolved we can give it one more run through CI

2026-07-20 16:24 UTC, diemol commented
Closing as superseded — this PR's goal (moving the inline Python locator examples into `examples/python/tests/elements/test_locators.py` and referencing them via `gh-codeblock`) was independently completed and merged in #2102, which landed a few days after this PR's last commit. Credit to @pmartinez1 for the original idea and effort here.

Trunk's `locators.en.md` (and the ja/pt-br/zh-cn translations) now reference `test_locators.py` for all locator examples — class name, CSS selector, ID, name, link text, partial link text, tag name, XPath, and relative locators — so there's nothing left to bring in from this branch.

2026-07-20 16:24 UTC, closed without merging