Added ElementClickInterceptedException to all languages
SeleniumHQ/seleniumhq.github.io pull request #1914
Opened 2024-08-29 22:21 UTC by shbenzer

Added section on ElementClickInterceptedException to all languages

### Description
Added ElementClickInterceptedException section to all languages in Understanding Common Errors

### Motivation and Context
feature #1276

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-08-29 22:22 UTC, shbenzer commented
happy to add more errors/exceptions if we like this

2024-09-12 00:32 UTC, shbenzer commented
@harsha509 is this pr missing anything? my plan is to slowly work my way through https://w3c.github.io/webdriver/#dfn-error-code

2024-09-12 01:00 UTC, harsha509 requested changes

2024-09-12 01:00 UTC, harsha509 commented on website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.en.md
> +Explicit waits will likely be your best friend in these instances. A great way is to use `ExpectedCondition.ToBeClickable()` with `WebDriverWait` to wait until the right moment.
[Explicit Wait]({{< ref "/documentation/webdriver/waits" >}}) 

we can have ref link to explicit wait

2024-09-12 01:00 UTC, harsha509 commented on website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.en.md
> +In instances where the element is out of view, but Selenium still registers the element as visible (e.g. navbars overlapping a section at the top of your screen), you can use the `WebDriver.executeSc
Could you please limit the line length to 100 characters as per the style guidelines

See _**Line length**_ in https://www.selenium.dev/documentation/about/style/

2024-09-12 02:54 UTC, shbenzer commented on website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.en.md
> +In instances where the element is out of view, but Selenium still registers the element as visible (e.g. navbars overlapping a section at the top of your screen), you can use the `WebDriver.executeSc
resolved

2024-09-12 02:54 UTC, shbenzer commented on website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.en.md
> +Explicit waits will likely be your best friend in these instances. A great way is to use `ExpectedCondition.ToBeClickable()` with `WebDriverWait` to wait until the right moment.
great idea. done.

2024-09-12 02:58 UTC, harsha509 approved these changes
Thank you @shbenzer !

2024-09-12 03:03 UTC, merged