Petesong/Add a Python example for the test practice
SeleniumHQ/seleniumhq.github.io pull request #1924
Opened 2024-09-05 02:58 UTC by PeteSong

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description
1. Correct the right link of Hugo Installation
2. Add a Python example for the test practices.

### Motivation and Context

For the test practices, there's no python example. 

### Types of changes

- [x] Change to the site 
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used `hugo server` to render the site/docs locally, but failed. Since I only have minor changes in the existing pages,  and I am sure it works.

2024-09-05 02:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1924) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1924) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1924) it.</sub>

2024-09-05 09:27 UTC, PeteSong commented
> ## PR Code Suggestions ✨
> Category	Suggestion                                                                                                                                   	Score
> **Best practice**	
> ✅ Use a context manager for WebDriver to ensure proper resource cleanup
> 9
> Use specific exception handling instead of a bare except clause
> 8
> ✅ Add assertions to verify initial state in test methods
> 7
> **Enhancement**	
> ✅ Convert static method to instance method for consistency and flexibility
> 5

Applied the suggestions.

2024-09-05 09:28 UTC, PeteSong commented
> ## PR Reviewer Guide 🔍
> ⏱️ **Estimated effort to review**: 4 🔵🔵🔵🔵⚪
> 🧪 **PR contains tests**
> 🔒 **No security concerns identified**
> ⚡ **Key issues to review**
> 
> [**Code Complexity**](https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1924/files#diff-ef76a0a38d2ead69e3cef4401392425717c886b9e7b638ede34872bf953aec22R381-R657)The added Python example is quite long and complex. Consider breaking it down into smaller, more manageable sections or separate files for better readability and maintainability.
> 
> [**Error Handling**](https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1924/files#diff-ef76a0a38d2ead69e3cef4401392425717c886b9e7b638ede34872bf953aec22R516-R523)The `is_loaded` method in the `TodoPage` class uses a bare except clause, which might catch and suppress unexpected errors. Consider using a more specific exception or at least logging the error.
> 
> [**Commented Code**](https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1924/files#diff-ef76a0a38d2ead69e3cef4401392425717c886b9e7b638ede34872bf953aec22R430-R434)There is commented out code in the `hover` method of the `ActionBot` class. Consider removing it if it's not needed or add a comment explaining why it's kept.

Applied the suggestions.

2024-09-18 14:44 UTC, shbenzer commented
Thank you for the contribution @PeteSong! Before it can be properly reviews a few things must be changed:
1. the example must be moved into a separate executable file like our other examples
2. the example must be properly formatted
3. the example must be propagated to all translations
4. lines must be kept to 100 characters per the style guide https://www.selenium.dev/documentation/about/style/

2024-09-26 10:51 UTC, PeteSong commented
> Thank you for the contribution @PeteSong! Before it can be properly reviewed a few things must be changed:
> 
> 1. the example must be moved into a separate executable file like our other examples
> 2. the example must be properly formatted like other examples to pull from the example file
> 3. the example must be propagated to all translations
> 4. lines must be kept to 100 characters per the style guide https://www.selenium.dev/documentation/about/style/

DONE

2024-09-26 14:11 UTC, shbenzer commented
> > Thank you for the contribution @PeteSong! Before it can be properly reviewed a few things must be changed:
> > 
> > 1. the example must be moved into a separate executable file like our other examples
> > 2. the example must be properly formatted like other examples to pull from the example file
> > 3. the example must be propagated to all translations
> > 4. lines must be kept to 100 characters per the style guide https://www.selenium.dev/documentation/about/style/
> 
> DONE

Awesome, thank you! @harsha1502

2024-10-25 19:39 UTC, A1exKH requested changes
@PeteSong please resolve conflicts for this PR.

2024-10-26 13:28 UTC, PeteSong commented
> @PeteSong please resolve conflicts for this PR.

DONE

2024-10-28 18:04 UTC, A1exKH approved these changes
LGTM.

2025-03-03 05:40 UTC, PeteSong commented
The merging is blocked, who could help me to merge it?

2025-03-03 05:43 UTC, PeteSong commented
@shbenzer, @A1exKH , 
Hope you are doing well. 

The merging is blocked for quite a time. What should I do or who could help me to merge it? 

Best regards,
Peter

2025-03-15 11:04 UTC, A1exKH commented
@PeteSong hi! 
You need a review and approval from people, who are contributors to this repository.

2025-03-17 15:19 UTC, shbenzer commented
Hello @PeteSong, thank you for your contributions!

I have added some review comments, let me know if you have any questions. The main point I'm trying to get across as you refactor the examples is that these are examples - they don't need to be fully fleshed out. 

Since you have provided a full seemingly working example in python - what we can instead do is utilize the codeblock architecture:

```
{{< gh-codeblock path="examples/python/tests/selenium_manager/usage.py#L10-L12" >}}
{{< /tab >}}
{{< tab header="CSharp" >}}
{{< badge-code >}}
{{< /tab >}}
{{< tab header="Ruby" >}}
{{< badge-code >}}
{{< /tab >}}
{{% tab header="JavaScript" %}}
```

and therefore use all the code you've written throughout the page (I personally prefer this alternative) - and this way we can keep the java example, as well.

If you just wish to use this final example of pulling together ActionBot, LoadableComponent, pytest, etc. then we just need the trimmed down final product so users can see a simple example.

2025-03-25 01:54 UTC, PeteSong commented
Hi @shbenzer ,

Thanks for your good comment. I have updated them per your suggestion. 

DONE!

Best regards,
Peter

> Hello @PeteSong, thank you for your contributions!
> 
> I have added some review comments, let me know if you have any questions. The main point I'm trying to get across as you refactor the examples is that these are examples - they don't need to be fully fleshed out.
> 
> Since you have provided a full seemingly working example in python - what we can _instead_ do is utilize the codeblock architecture:
> 
> ```
> {{< gh-codeblock path="examples/python/tests/selenium_manager/usage.py#L10-L12" >}}
> {{< /tab >}}
> {{< tab header="CSharp" >}}
> {{< badge-code >}}
> {{< /tab >}}
> {{< tab header="Ruby" >}}
> {{< badge-code >}}
> {{< /tab >}}
> {{% tab header="JavaScript" %}}
> ```
> 
> and therefore use all the code you've written throughout the page (I personally prefer this alternative) - and this way we can keep the java example, as well.

2025-04-13 13:11 UTC, PeteSong commented
@shbenzer 
Hope you are doing well. Could you be kind to review the changes and approve the PR? Thank you very much

Best regards,
Peter

2025-04-13 16:47 UTC, shbenzer commented
Hey @PeteSong this looks good! Only thing I notice atm that needs to be changed is that you're missing the other languages in the codeblock elements. We use those so that readers can see where examples are missing and for ease of contributions.

2025-04-14 03:01 UTC, PeteSong commented
Good suggestion! DONE!

> Hey @PeteSong this looks good! Only thing I notice atm that needs to be changed is that you're missing the other languages in the codeblock elements. We use those so that readers can see where examples are missing and for ease of contributions.

2025-04-14 16:21 UTC, shbenzer commented
LGTM 

@harsha509 I don’t seem to have permissions to this repo, could you take a look?

2025-04-20 02:09 UTC, PeteSong commented
Hi @harsha509, hope you are doing well!  Could I trouble you to take some time to review and merge it?  Thank you very much.

2025-05-03 14:35 UTC, shbenzer commented
Alright, after pulling locally there's a few more changes that need to be made and you'll be good to go.

1. lets put all examples in the codeblock elements
2. in the codeblock elements, make sure that each language without an example has a badgecode so we can help facilitate contributions

2025-05-04 11:16 UTC, PeteSong commented
> Alright, now that I have permissions I pulled locally. There's a few more changes that need to be made and you'll be good to go.
> 
> 1. lets put all examples in the codeblock elements
> 2. in the codeblock elements, make sure that each language without an example has a badgecode so we can help facilitate contributions

Hi @shbenzer, for 1),  I already put all my examples in the codeblock elements. for 2), what is the badgecode? could you show me an example?

2025-05-04 16:44 UTC, shbenzer commented
> Hi @shbenzer, for 1), I already put all my examples in the codeblock elements. 

That's correct! However, now that we're using multiple languages in this document, it'd be best to put the other code examples you didn't alter into codeblocks so the page is consistently formatted.

> for 2), what is the badgecode? could you show me an example?

Gladly!

Badge codes have this structure in codeblocks:

```html
{{< tab header="JavaScript" >}}
{{< badge-code >}}
{{< /tab >}}
```

and they produce this when rendered:

<img width="639" alt="Screenshot 2025-05-04 at 12 40 27 PM" src="https://github.com/user-attachments/assets/8db52a0c-c80d-49db-b9c8-18ba203ccfa9" />

Clicking the link then takes you to the [creating examples section](https://www.selenium.dev/documentation/about/contributing/#creating-examples) of [the contribution guide](https://www.selenium.dev/documentation/about/contributing/)

2025-05-05 08:28 UTC, PeteSong commented
Hi @shbenzer,  hope you are doing well.
1. for now, only one example in Python. 
2. added the badgecode. 


Best regards,
Peter

2025-05-05 15:47 UTC, shbenzer commented
> Hi @shbenzer, hope you are doing well.
> 
> 1. for now, only one example in Python.
> 2. added the badgecode.
> 
> Best regards, Peter

Regarding 1, that's not what I meant, but it can be done in another PR.

LGTM

2025-05-05 15:48 UTC, merged

2025-05-05 16:23 UTC, shbenzer commented
Thank you @PeteSong !