Add documentation to show the alternative use of an environment variable
SeleniumHQ/seleniumhq.github.io pull request #1950
Opened 2024-09-18 16:43 UTC by aguspe

### Description

This PR adds to the selenium_manager a section that clarifies how to use environment variables as an alternative to set up the driver path

### Motivation and Context

After this feature was added https://github.com/SeleniumHQ/selenium/pull/14287 we need to update our documentation to reflect the possibility to use env variables to set the driver as an alternative to Selenium manager for the Selenium users

### Types of changes
- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist
- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-09-18 18:29 UTC, Delta456 approved these changes

2024-09-18 22:32 UTC, harsha509 requested changes

2024-09-18 22:32 UTC, harsha509 commented on website_and_docs/content/documentation/selenium_manager.en.md
> +For example, to specify the path to the chromedriver, you can set the `SE_CHROMEDRIVER` environment variable to the path of the chromedriver executable.
Hi @aguspe ,

Thank you for the PR.
Could you please limit the line length to 100 characters as per the style guidelines
See Line length in https://www.selenium.dev/documentation/about/style/

Thanks,
Sri

2024-09-19 13:44 UTC, p0deje approved these changes

2024-09-20 07:52 UTC, aguspe commented
Ready for re-review @harsha509

2024-09-20 10:35 UTC, harsha509 approved these changes
Thank you @aguspe !

2024-09-20 10:39 UTC, merged