Added Java Example
SeleniumHQ/seleniumhq.github.io pull request #1966
Opened 2024-09-24 17:39 UTC by shbenzer

Added Java example to Selenium Manager

### Description
Created usage.java with selenium manager examples
added examples to all translations

### Motivation and Context
increase site comprehensiveness

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-10-25 19:42 UTC, A1exKH approved these changes
LGTM.

2025-01-03 06:04 UTC, harsha509 approved these changes
Thank you @shbenzer !

2025-01-03 06:07 UTC, harsha509 requested changes

2025-01-03 06:07 UTC, harsha509 commented on examples/java/src/test/java/dev/selenium/selenium_manager/usage.java
> +public class usage {
```suggestion
public class SeleniumManagerUsageDemo {
```

2025-01-03 17:32 UTC, shbenzer commented
@harsha509 changed

2025-01-06 10:59 UTC, harsha509 approved these changes
Thank you @shbenzer !

2025-01-06 10:59 UTC, merged