Added CSharp Example to Selenium Manager
SeleniumHQ/seleniumhq.github.io pull request #1967
Opened 2024-09-24 17:57 UTC by shbenzer

Added CSharp Example to Selenium Manager section

### Description
created TestUsage.cs
Added example scripts to index.md for all translations

### Motivation and Context
Make site more comprehensive

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-10-25 19:41 UTC, A1exKH approved these changes
LGTM.

2025-02-25 19:48 UTC, nvborisenko requested changes
We should propagate good patterns in examples. Particularly here we should `Dispose()` allocated object.

2025-02-25 19:48 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            ChromeDriver driver = new ChromeDriver("path/to/ChromeDriver");
```suggestion
            using driver = new ChromeDriver("path/to/ChromeDriver");
```

2025-02-25 19:48 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            driver.Quit();
`.Quit()` is unnecessary, it is better to propagate `using` statement.

2025-02-25 19:48 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            ChromeDriver driver = new ChromeDriver();
Please apply `using` pattern as I proposed in comments above.

2025-02-26 00:21 UTC, shbenzer commented
@nvborisenko I believe this is correct now

2025-02-26 19:24 UTC, nvborisenko requested changes
Thanks, we are closer to correct example.

2025-02-26 19:24 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +    public class UsageTest : BaseChromeTest
We don't need to inherit from base class. Tests here start own driver.

2025-02-26 19:24 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            using ChromeDriver driver = new ChromeDriver("path/to/ChromeDriver");
In the next version of Selenium, it will throw exception because `path/to/ChromeDriver` is incorrect path.

I propose to do something like (in one test):
```csharp
// Before
// using var driver = new ChromeDriver("path/to/ChromeDriver");

// After
using var driver = new ChromeDriver();
```

2025-02-26 23:47 UTC, shbenzer commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            using ChromeDriver driver = new ChromeDriver("path/to/ChromeDriver");
That's a good point, I'll make an adjustment

2025-02-27 22:22 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +        // public void TestWithoutSeleniumManager()
Can we highlight only one line diff? Instead of commenting out the whole test?

2025-02-28 17:41 UTC, RenderMichael requested changes
Code example looks great, a small adjustment on the doc files themselves

2025-02-28 17:41 UTC, RenderMichael commented on website_and_docs/content/documentation/selenium_manager.en.md
> +{{< gh-codeblock path="examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs#L22-L27" >}}
The line numbers should align with the specific code we want to show users

```suggestion
{{< gh-codeblock path="examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs#L18" >}}
**Selenium Manager**
{{< gh-codeblock path="examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs#L21" >}}
```

Same for all four language versions

2025-02-28 18:25 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            // using ChromeDriver driver = new ChromeDriver("path/to/ChromeDriver");
```suggestion
            // using var driver = new ChromeDriver("path/to/ChromeDriver");
```

2025-02-28 18:25 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            using ChromeDriver driver = new ChromeDriver();
```suggestion
            using var driver = new ChromeDriver();
```

2025-03-02 19:37 UTC, shbenzer commented on website_and_docs/content/documentation/selenium_manager.en.md
> +{{< gh-codeblock path="examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs#L22-L27" >}}
Yep, was waiting to do that until after code example was given the ok

2025-03-02 19:37 UTC, shbenzer commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            using ChromeDriver driver = new ChromeDriver();
Shouldn't we be more explicit in an example?

2025-03-02 19:38 UTC, shbenzer commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            // using ChromeDriver driver = new ChromeDriver("path/to/ChromeDriver");
Same question as below

2025-03-02 20:00 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            using ChromeDriver driver = new ChromeDriver();
More explicit is `global::OpenQA.Selenium.Chrome.ChromeDriver`. Just believe me: `var` here is very good.

2025-03-03 00:47 UTC, shbenzer commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +            using ChromeDriver driver = new ChromeDriver();
ok

2025-03-03 00:48 UTC, shbenzer commented
@nvborisenko Is this example good? I'll need to update the referenced lines in the code examples for each translation before I can push

2025-03-03 09:43 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +namespace SeleniumDocs.Support
```suggestion
namespace SeleniumDocs.SeleniumManager
```

2025-03-03 09:44 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +using Microsoft.VisualStudio.TestTools.UnitTesting;
Please review `usings` and remove unused.

2025-03-03 09:47 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +using Microsoft.VisualStudio.TestTools.UnitTesting;
![image](https://github.com/user-attachments/assets/2663d241-0e7a-4dd7-8d8d-5fe7b7401f86)

2025-03-03 09:48 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +        public void TestWithSeleniumManager()
Missing `[TestMethod]` attribute.

2025-03-03 17:58 UTC, nvborisenko commented
C# example looks good, thank you. Don't forget to update line numbers (I think it will be one code block).

2025-03-03 22:38 UTC, RenderMichael commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +namespace SeleniumDocs.SeleniumManager
`SeleniumManager` is clashing with the type of the same name in selenium 

```suggestion
namespace SeleniumDocs.SeleniumManagerTest
```

2025-03-04 00:51 UTC, RenderMichael commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +namespace SeleniumDocs.SeleniumManager
(the name I put is just a suggestion)

2025-03-04 04:14 UTC, nvborisenko commented on examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
> +namespace SeleniumDocs.SeleniumManager
It is not a problem.

2025-05-03 13:31 UTC, shbenzer commented
Failures unrelated:

```
Error: /home/runner/work/seleniumhq.github.io/seleniumhq.github.io/examples/dotnet/SeleniumDocs/BiDi/CDP/NetworkTest.cs(7,32): error CS0234: The type or namespace name 'V132' does not exist in the namespace 'OpenQA.Selenium.DevTools' (are you missing an assembly reference?) [/home/runner/work/seleniumhq.github.io/seleniumhq.github.io/examples/dotnet/SeleniumDocs/SeleniumDocs.csproj]
  Error: /home/runner/work/seleniumhq.github.io/seleniumhq.github.io/examples/dotnet/SeleniumDocs/BiDi/CDP/NetworkTest.cs(8,32): error CS0[23](https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/14811129818/job/41585905395?pr=1967#step:11:24)4: The type or namespace name 'V132' does not exist in the namespace 'OpenQA.Selenium.DevTools' (are you missing an assembly reference?) [/home/runner/work/seleniumhq.github.io/seleniumhq.github.io/examples/dotnet/SeleniumDocs/SeleniumDocs.csproj]
  Warning: Attempt 1 failed. Reason: Child_process exited with error code 1
  ```

2025-05-03 13:39 UTC, merged