Added ElementNotInteractableException to Common Errors
SeleniumHQ/seleniumhq.github.io pull request #1972
Opened 2024-09-24 19:17 UTC by shbenzer

Added ElementNotInteractableException to Common Errors docs

### Description
updated index.md in all translations with ElementNotInteractableException

### Motivation and Context
make docs more comprehensive

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-10-22 15:00 UTC, shbenzer commented
issue #1276

2024-11-11 18:18 UTC, shbenzer commented
@harsha509 what do you think?

2024-11-29 22:27 UTC, A1exKH approved these changes
@shbenzer PR LGTM.

2025-01-15 22:30 UTC, A1exKH requested changes
@shbenzer please resolve conflicts for this PR.

2025-01-15 22:54 UTC, shbenzer commented
@A1exKH  It looks like another pr was merged that provides the same content. I'll close this.

2025-01-15 22:54 UTC, closed without merging