Update navigation.en.md
SeleniumHQ/seleniumhq.github.io pull request #1997
Opened 2024-10-14 14:18 UTC by Rupesh253

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-10-14 14:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1997) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=1997) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=1997) it.</sub>

2024-10-16 16:41 UTC, shbenzer commented
Thank you for your contribution @Rupesh253 !

First off, before any of your PRs can be merged, you must sign the Contributor License Agreement.

Second, it looks like this pr is based on your other PR #1996. You will need to merge these prs into one single pr for them to be accepted.

2024-10-23 14:45 UTC, A1exKH requested changes
@Rupesh253 
please check [this comment (click)](https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1997#issuecomment-2417370683) and address required changes in your PR.

2024-11-01 15:05 UTC, harsha509 commented
Hi @Rupesh253,

Thank you for your contribution!

I appreciate the effort to clarify the differences between driver.Url and driver.Navigate().GoToUrl. However, for the context provided, our goal is to show the usage of both driver.Url and driver.Navigate().GoToUrl, without detailing the types of arguments they accept. Including the additional notes on Uri and string arguments may add unnecessary complexity for our intended audience in docs.

For simplicity and consistency, we'll keep the original explanations focused on basic usage examples. Thanks again for the suggestion, and we welcome further contributions!

Closing as Not Planned!

2024-11-01 15:05 UTC, closed without merging