docs/selenium_manager: mention about Python now supporting ENV for driver path
SeleniumHQ/seleniumhq.github.io pull request #2055
Opened 2024-11-11 09:42 UTC by Delta456

…iver path

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

Mentions Python support for setting ENV for driver path

### Motivation and Context

New implemented feature which needs to be documented

<img width="916" alt="image" src="https://github.com/user-attachments/assets/d86f6780-ec3b-4cb3-a4a7-9ec103d957fa">

### Types of changes

- [x] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-11-11 18:00 UTC, harsha509 approved these changes
Thank you @Delta456 !

2024-11-11 18:00 UTC, harsha509 commented on website_and_docs/content/documentation/selenium_manager.pt-br.md
> +This feature is available in the Selenium Ruby and Python binding starting from version 4.25.0 and 4.26.0.
This feature is available in the Selenium Ruby binding starting from version 4.25.0 and in the Python binding from version 4.26.0.

2024-11-11 18:00 UTC, harsha509 commented on website_and_docs/content/documentation/selenium_manager.zh-cn.md
> +This feature is available in the Selenium Ruby and Python binding starting from version 4.25.0 and 4.26.0.
same here

2024-11-11 18:00 UTC, harsha509 commented on website_and_docs/content/documentation/selenium_manager.ja.md
> +This feature is available in the Selenium Ruby and Python binding starting from version 4.25.0 and 4.26.0.
This feature is available in the Selenium Ruby binding starting from version 4.25.0 and in the Python binding from version 4.26.0.

2024-11-11 18:00 UTC, harsha509 commented on website_and_docs/content/documentation/selenium_manager.en.md
> +This feature is available in the Selenium Ruby and Python binding starting from version 4.25.0 and 4.26.0.
This feature is available in the Selenium Ruby binding starting from version 4.25.0 and in the Python binding from version 4.26.0.

2024-11-11 18:01 UTC, harsha509 requested changes
HI @Delta456 ,

Thank you for the PR. Requested few changes!

2024-11-11 18:59 UTC, Delta456 commented on website_and_docs/content/documentation/selenium_manager.pt-br.md
> +This feature is available in the Selenium Ruby and Python binding starting from version 4.25.0 and 4.26.0.
Sounds good!

2024-11-11 18:59 UTC, Delta456 commented on website_and_docs/content/documentation/selenium_manager.zh-cn.md
> +This feature is available in the Selenium Ruby and Python binding starting from version 4.25.0 and 4.26.0.
Sure

2024-11-12 13:32 UTC, harsha509 approved these changes
Thank you @Delta456 !

2024-11-12 13:32 UTC, merged