[py]: move python code to `test_locators.py`
SeleniumHQ/seleniumhq.github.io pull request #2102
Opened 2024-12-16 09:20 UTC by navin772

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to review and merge it quickly**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, and help reviewers by making them as simple and short as possible.

### Description

Moved python code of locators to `test_locators.py` and 

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2024-12-16 18:00 UTC, harsha509 requested changes
HI Navin,

Thank you for the PR. Could you please look into comments provided.

Thanks,
Sri

2024-12-16 18:00 UTC, harsha509 commented on examples/python/tests/elements/locators.html
We don't place HTML code here. Instead, you can use the static pages deployed on the official Selenium website
https://www.selenium.dev/selenium/web/

2024-12-17 03:50 UTC, navin772 commented on examples/python/tests/elements/locators.html
Can't find a similar html page, so created a PR to add it in selenium - https://github.com/SeleniumHQ/selenium/pull/14905

2024-12-26 11:14 UTC, navin772 commented on examples/python/tests/elements/locators.html
Updated the PR to use - https://www.selenium.dev/selenium/web/locators_tests/locators.html which was added recently

2024-12-28 08:37 UTC, yvsvarma approved these changes
Thanks for these additions! They are well-structured and help clarify the documentation. Looks good to merge.

2024-12-28 08:41 UTC, harsha509 approved these changes

2024-12-28 08:41 UTC, harsha509 approved these changes
Thank you @navin772 !

2024-12-28 09:19 UTC, merged