Sample of Get Element CSS Value
SeleniumHQ/seleniumhq.github.io pull request #527
Opened 2020-09-22 14:43 UTC by Peyton88

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2020-09-22 14:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=527) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=527) before we can accept your contribution.<br/><hr/>**peyton_fang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=527) it.</sub>

2020-09-23 17:56 UTC, Harsha509 requested changes
Hi @Peyton88 ,

Thanks for the PR!

get Element css value actually returns a value of computed css style property of an element. we have WebDriver method like `getCssValue` in JS. The code sample you've provided is for `getAttribute`

i've updated doc with a code sample for JS. https://www.selenium.dev/documentation/fr/webdriver/web_element/#get-element-css-value

can you please update the code samples accordingly.

Thank you !

2020-09-24 16:58 UTC, Peyton88 commented
> Hi @Peyton88 ,
> 
> Thanks for the PR!
> 
> get Element css value actually returns a value of computed css style property of an element. we have WebDriver method like `getCssValue` in JS. The code sample you've provided is for `getAttribute`
> 
> i've updated doc with a code sample for JS. https://www.selenium.dev/documentation/fr/webdriver/web_element/#get-element-css-value
> 
> can you please update the code samples accordingly.
> 
> Thank you !

Thanks. I got a misunderstanding.
I've updated my commit.

2020-09-24 18:05 UTC, Harsha509 requested changes
hi @Peyton88 ,

Thank you for making the changes. and apologies again for reverting it, there are couple of things required to get this pr merged !

1. Can you please fill/complete the above checklist.
2. Semicolons are not required in few language bindings like kotlin, ruby, python can you please look into the suggested changes
3. Can you please make the same changes in other translated pages too like (es,fr,zh-cn).

Thank you!

2020-09-24 18:05 UTC, harsha509 commented on docs_source_files/content/webdriver/web_element.en.md
> +cssValue = driver.find_element(:link_text, 'More information...').css_value('color');
```suggestion
cssValue = driver.find_element(:link_text, 'More information...').css_value('color')
```

2020-09-24 18:05 UTC, harsha509 commented on docs_source_files/content/webdriver/web_element.en.md
> +driver.get('https://www.example.com');
```suggestion
driver.get('https://www.example.com')
```

2020-09-24 18:05 UTC, Harsha509 commented on docs_source_files/content/webdriver/web_element.en.md
> +cssValue = driver.findElement(By.LINK_TEXT, "More information...").value_of_css_property('color');
```suggestion
cssValue = driver.findElement(By.LINK_TEXT, "More information...").value_of_css_property('color')
```

2020-09-24 18:05 UTC, Harsha509 commented on docs_source_files/content/webdriver/web_element.en.md
> +driver.get('https://www.example.com');
```suggestion
driver.get('https://www.example.com')
```

2020-09-24 18:05 UTC, Harsha509 commented on docs_source_files/content/webdriver/web_element.en.md
> +val cssValue = driver.findElement(By.linkText("More information...")).getCssValue('color');
```suggestion
val cssValue = driver.findElement(By.linkText("More information...")).getCssValue('color')
```

2020-09-26 16:45 UTC, Peyton88 commented
> hi @Peyton88 ,
> 
> Thank you for making the changes. and apologies for reverting it, there are couple of things required to get this pr merged !
> 
> 1. Can you please fill/complete the above checklist.
> 2. Semicolons are not required in few language bindings like kotlin, ruby, python can you please look into the suggested changes
> 3. Can you please make the same changes in other translated pages too like (es,fr,zh-cn).
> 
> Thank you!

Hi Harsha509,

Thanks for your kindly reminding.
Please see my updates.

2020-09-27 08:16 UTC, Harsha509 approved these changes
Thank you @Peyton88 !

2020-09-27 08:21 UTC, Harsha509 commented
deploy-preview looks good !

2020-09-27 08:21 UTC, merged

2020-09-27 08:25 UTC, Harsha509 commented
Congratulations on your first contribution @Peyton88  🎉  🎉  🎉  🎉  🎉

2020-09-27 12:50 UTC, Peyton88 commented
> Congratulations on your first contribution @Peyton88 🎉 🎉 🎉 🎉 🎉

Thanks you~