Adding JS snippet to HTTP Proxies docs in english
SeleniumHQ/seleniumhq.github.io pull request #534
Opened 2020-10-13 14:16 UTC by paultheprogrammer

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2020-10-13 14:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=534) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=534) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=534) it.</sub>

2020-10-14 14:48 UTC, Harsha509 requested changes
Hi @paultheprogrammer,

Thanks for the PR.

1. Can you adjust the code sample to use ChromeOptions to set proxy and not using withCapabilities. (like Java code sample)

2. Can you add code sample to other translated pages to which are not in English like es, du, zh-cn etc

2020-10-24 16:22 UTC, Harsha509 commented
Hi @paultheprogrammer ,

As the PR went stale. I have replaced the code sample with this [commit](https://github.com/SeleniumHQ/seleniumhq.github.io/commit/1479b305d7fc381f001e43811cad4cb764c7e788) 

Thank you!

2020-10-24 16:22 UTC, closed without merging

2020-10-24 17:28 UTC, paultheprogrammer commented
No worries. Glad that you added the code snippets to the docs!

Best regards,
@paultheeprogrammer

On Saturday, October 24, 2020, Sri Harsha <notifications@github.com> wrote:

> Closed #534 <https://github.com/SeleniumHQ/seleniumhq.github.io/pull/534>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/SeleniumHQ/seleniumhq.github.io/pull/534#event-3916898735>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARFVGEN23N3J2P4GZWGVIS3SML5O5ANCNFSM4SO6VNCA>
> .
>