closes #533
SeleniumHQ/seleniumhq.github.io pull request #535
Opened 2020-10-13 17:34 UTC by skyhirider

described attachment download option via HtmlUnit

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
closes #533 
### Motivation and Context

as mentioned in issue, a lot of people are looking to download files from ajax sites and selenium + htmlunit is one of the few options available if you asynchronously receive a download response
### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2020-10-13 17:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=535) <br/>All committers have signed the CLA.

2020-10-14 05:11 UTC, Harsha509 requested changes, later dismissed
hi @skyhirider !

Thanks for the PR !

Can you please make same changes in other translated pages too (like es, zh-cn etc)

2020-10-14 17:09 UTC, skyhirider commented
@Harsha509 You mean translate it? Best I could do is run it through google translate, did you mean that?

My native tongue is Slovak and have a limited grasp of German, and that is pretty much it.

2020-10-14 17:44 UTC, diemol commented
@skyhirider I replied here
https://github.com/SeleniumHQ/seleniumhq.github.io/issues/533#issuecomment-708016220

2020-11-03 06:48 UTC, JS31096 commented
Hi @skyhirider ,

Did you get a chance to look into the above comments/suggestions ?

2020-11-03 07:57 UTC, skyhirider commented
Hi @JS31096 I will have a look, still want to make the change just need to find time to do it.

2020-11-08 12:35 UTC, skyhirider commented
@JS31096 added English text to other language versions with the disclaimer. Also ticked the checkbox for the CLA

2020-11-08 21:40 UTC, diemol commented on docs_source_files/content/worst_practices/file_downloads.es.md
> +English to {LANGUAGE}. Do you speak {LANGUAGE}? Help us to translate
```suggestion
English to Spanish. Do you speak Spanish? Help us to translate
```

2020-11-08 21:40 UTC, diemol commented on docs_source_files/content/worst_practices/file_downloads.fr.md
> +English to {LANGUAGE}. Do you speak {LANGUAGE}? Help us to translate
```suggestion
English to French. Do you speak French? Help us to translate
```

2020-11-08 21:42 UTC, diemol commented on docs_source_files/content/worst_practices/file_downloads.ja.md
> +English to {LANGUAGE}. Do you speak {LANGUAGE}? Help us to translate
```suggestion
English to Japanese. Do you speak Japanese? Help us to translate
```

2020-11-08 21:43 UTC, diemol commented on docs_source_files/content/worst_practices/file_downloads.ko.md
> +English to {LANGUAGE}. Do you speak {LANGUAGE}? Help us to translate
```suggestion
English to Korean. Do you speak Korean? Help us to translate
```

2020-11-08 21:44 UTC, diemol commented on docs_source_files/content/worst_practices/file_downloads.nl.md
> +{{% /notice %}}
```suggestion
```

2020-11-08 21:44 UTC, diemol commented on docs_source_files/content/worst_practices/file_downloads.zh-cn.md
> +English to {LANGUAGE}. Do you speak {LANGUAGE}? Help us to translate
```suggestion
English to Chinese. Do you speak Chinese? Help us to translate
```

2020-11-08 21:44 UTC, diemol approved these changes

2020-11-08 21:45 UTC, merged