Syntax error for Java code
SeleniumHQ/seleniumhq.github.io pull request #587
Opened 2020-12-22 12:45 UTC by selfishone

In Java static variables cant be used in a non static method/ constructor

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2020-12-22 12:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=587) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=587) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=587) it.</sub>

2020-12-22 23:12 UTC, diemol requested changes
@selfishone, could you please elaborate why this PR is needeed? Also, can you please update the files in other languages?
- page_object_models.es.md 
- page_object_models.de.md 
- etc...

2020-12-30 06:33 UTC, JS31096 commented
Hi @selfishone,

Did you get a chance to look into the above comments?

2021-01-11 16:46 UTC, JS31096 commented
Hi @selfishone ,

As the PR went stale, i have replaced the change with this [commit](https://github.com/SeleniumHQ/seleniumhq.github.io/commit/4fcfba21cfe936d8140b06dd30ad5f356380f0ac) 

Thank you !

2021-01-11 16:46 UTC, closed without merging