Add Print API to Browser Manipulation Page
SeleniumHQ/seleniumhq.github.io pull request #606
Opened 2021-01-07 14:37 UTC by AutomatedTester

### Description
Add the newly created Print API to browser manipulation page. 

### Motivation and Context
Adds a new API

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [x] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

Note, this currently only has the python example.

2021-01-07 14:41 UTC, diemol requested changes
Thank you, @AutomatedTester!
Could you please add this text to the other `browser_manipulation.*.md` files?

You can add a notification above the text asking for help translating it, something like:
```
{% notice info %}} Page being translated from English to Dutch. Do you speak Dutch? Help us to translate it by sending us pull requests! {{% /notice %}}
```

2021-01-09 16:32 UTC, JS31096 approved these changes
Thank you @AutomatedTester!

2021-01-09 16:33 UTC, JS31096 approved these changes
Thank you @AutomatedTester!

2021-01-19 13:26 UTC, diemol approved these changes

2021-01-19 13:26 UTC, merged