Python code added under Emulate Geo Location
SeleniumHQ/seleniumhq.github.io pull request #612
Opened 2021-01-12 11:20 UTC by Saketspradhan

Working fine

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [x] Code example added (for Python)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2021-01-12 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=612) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=612) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=612) it.</sub>

2021-01-13 15:31 UTC, baqua10 approved these changes

2021-01-13 15:31 UTC, baqua10 submitted a review, later dismissed

2021-01-20 10:02 UTC, JS31096 requested changes
Hi @Saketspradhan,

Thanks for the PR.
I've requested for couple of changes, can you please look into it.

Also can you add the code sample to other translated pages (like es, zh-cn etc)

2021-01-20 10:02 UTC, harsha509 commented on docs_source_files/content/support_packages/chrome_devtools.en.md
> +PATH = "SPECIFY YOUR CHROMEDRIVER.EXE PATH HERE"
Can you remove this line?

All code samples are written assuming that the driver paths are already set up in the machine.

2021-01-20 10:02 UTC, JS31096 commented on docs_source_files/content/support_packages/chrome_devtools.en.md
> +    driver = webdriver.Chrome(PATH)
The above line can be modified if the path is removed!

2021-01-20 10:33 UTC, Saketspradhan commented on docs_source_files/content/support_packages/chrome_devtools.en.md
> +PATH = "SPECIFY YOUR CHROMEDRIVER.EXE PATH HERE"
Done.

2021-01-20 10:35 UTC, Saketspradhan commented
Do I have to create separate PRs for every translated page?

2021-01-20 12:29 UTC, JS31096 commented
> Do I have to create separate PRs for every translated page?

No Please update the same PR with the code samples in other translated pages!

2021-01-22 03:16 UTC, JS31096 commented
Hi @Saketspradhan,

Did you get a chance to look into above comments?

2021-01-23 16:49 UTC, JS31096 approved these changes
Thank you @Saketspradhan!

I will add the code sample to other translated pages with another commit referring to this PR.

2021-01-23 16:50 UTC, merged

2021-01-23 17:42 UTC, JS31096 commented
Congratulations on your first PR to Selenium Docs @Saketspradhan 🎉 🎉 🥳 🥳