Translated "Update _index.ko.md" from English to Korean
SeleniumHQ/seleniumhq.github.io pull request #613
Opened 2021-01-17 17:57 UTC by joft-ware

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Translated "Update _index.ko.md" from English to Korean

### Motivation and Context

Missing translation

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [x] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2021-01-17 17:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=613) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=613) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=613) it.</sub>

2021-01-17 19:14 UTC, diemol commented
Thank you, @joft-ware!
Could you please sign the CLA so I can merge this right away?

2021-01-18 00:28 UTC, joft-ware commented
Sure! I just signed

2021-01-18 05:00 UTC, JS31096 requested changes
Hi @joft-ware,

Thank you for the PR. Can you please look into the suggestions.

Thanks!

2021-01-18 05:00 UTC, harsha509 commented on docs_source_files/content/remote_webdriver/_index.ko.md
> +클라이언트는 당신의 WebDriver teset이며 서버는 간단한 Java servelet의 일종이고 JEE app 서버에 호스팅될 수 있습니다.
Servlet

2021-01-18 05:58 UTC, joft-ware commented on docs_source_files/content/remote_webdriver/_index.ko.md
> +클라이언트는 당신의 WebDriver teset이며 서버는 간단한 Java servelet의 일종이고 JEE app 서버에 호스팅될 수 있습니다.
Sorry I just fixed it

2021-01-18 12:35 UTC, JS31096 approved these changes
Thank you @joft-ware!

2021-01-18 12:36 UTC, merged