Update two_factor_authentication.ko.md
SeleniumHQ/seleniumhq.github.io pull request #661
Opened 2021-04-15 13:07 UTC by lvninety

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

translated 2FA

### Description
translated 2FA

### Motivation and Context
2FA doc needed to be translated

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [x] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2021-04-16 04:11 UTC, JS31096 requested changes
HI @lvninety ,

Thanks for the PR. I have provided few comments can you please look into it.

2021-04-16 04:11 UTC, JS31096 commented on docs_source_files/content/worst_practices/two_factor_authentication.ko.md
> +title: "2단계 인증(2FA)"
Two단계 인증(2FA)

This can be in English if we cannot translate the word.

2021-04-16 04:11 UTC, JS31096 commented on docs_source_files/content/worst_practices/two_factor_authentication.ko.md
> +title: "2단계 인증(2FA)"
Also we can remove the translation message header `{{% notice info %}} Page being translated from English to Korean. Do you speak Korean? Help us to translate it by sending us pull requests! {{% /notice %}}` if the document is fully translated

2021-04-17 15:00 UTC, lvninety commented on docs_source_files/content/worst_practices/two_factor_authentication.ko.md
> +title: "2단계 인증(2FA)"
We usually call Two Factor Authentication "2단계 인증" in Korean. Also it is called "2FA". Thus, there is no issue to translate any words. But I improved translation to avoid words being mixed.
And as you said,  I removed message header as the doc is fully translated in Korean. :-)

2021-04-17 15:59 UTC, JS31096 approved these changes
Thank you @lvninety !

2021-04-17 15:59 UTC, merged