POM_Spanish.md
SeleniumHQ/seleniumhq.github.io pull request #766
Opened 2021-09-19 11:21 UTC by crisgilla

Modelos de objetos página (Page object models POM):
/*This offers a translation into Spanish of the page https://www.selenium.dev/es/documentation/guidelines/page_object_models/
*/
/*
* El patrón objeto página es un patrón de diseño que se ha hecho popular en la automatización de
* pruebas para mejorar el mantenimiento de las mismas y reducir la duplicación de
* código. Un objeto página es una clase orientada a objetos que sirve de interfaz
* a una página de su UAT. Las pruebas utilizan los métodos de esta clase objeto
* página cada vez que necesitan interactuar con la interfaz de usuario de esa
* página. La ventaja es que si la interfaz de usuario de la página cambia, las
* pruebas no tienen que cambiar, sólo el código dentro de ese objeto página tiene
* que cambiar. Posteriormente, todos los cambios para soportar esa nueva interfaz
* de usuario se encuentran en un solo lugar.
*El patrón de diseño de objetos página ofrece las siguientes ventajas:
*  1.-   Hay una separación limpia entre el código de prueba y el código específico de la página, como los localizadores (o su uso
*  si se utiliza un mapa de interfaz de usuario) y el diseño.
*   2.- Existe un único repositorio para los servicios u operaciones que ofrece la página en lugar de tener estos servicios
*  dispersos por las pruebas.
*
* En ambos casos, esto
* permite que las modificaciones necesarias debido a los cambios en la interfaz
* de usuario se realicen en un solo lugar. Se puede encontrar información útil
* sobre esta técnica en numerosos blogs, ya que este "patrón de diseño de
* pruebas" se está utilizando ampliamente. Animamos al lector que desee
* saber más a que busque en Internet blogs sobre este tema. Muchos han escrito
* sobre este patrón de diseño y pueden proporcionar consejos útiles que van más
* allá del alcance de esta guía de usuario. Sin embargo, para empezar,
* ilustraremos los objetos página con un ejemplo sencillo.
* Primero, consideremos un ejemplo, típico de la automatización de pruebas, que no utiliza un objeto página:

*/
/***
 * Tests login feature
 */
public class Login {

  public void testLogin() {
    // fill login data on sign-in page
    driver.findElement(By.name("user_name")).sendKeys("testUser");
    driver.findElement(By.name("password")).sendKeys("my supersecret password");
    driver.findElement(By.name("sign-in")).click();

    // verify h1 tag is "Hello userName" after login
    driver.findElement(By.tagName("h1")).isDisplayed();
    assertThat(driver.findElement(By.tagName("h1")).getText(), is("Hello userName"));
  }
}
/** Este enfoque conlleva dos
* problemas.
* No hay separación entre el método de prueba y los localizadores
* del AST  (Aplicación Sometida a Test -
* AUT). Si la interfaz de usuario del AST cambia sus identificadores, su diseño o
* la forma en que se introduce y procesa un inicio de sesión, la propia prueba
* debe cambiar.
* Los identificadores se repartirían en varias pruebas, en todas
* las pruebas que tuvieran que utilizar esta página de inicio de sesión.
* Aplicando las técnicas de objetos
* página, este ejemplo podría reescribirse así en el siguiente ejemplo de objeto
* página para una página de inicio de sesión.
*/
/**
 * Page Object encapsulates the Sign-in page.
 */
public class SignInPage {
  protected WebDriver driver;

  // <input name="user_name" type="text" value="">
  private By usernameBy = By.name("user_name");
  // <input name="password" type="password" value="">
  private By passwordBy = By.name("password");
  // <input name="sign_in" type="submit" value="SignIn">
  private By signinBy = By.name("sign_in");

  public SignInPage(WebDriver driver){
    this.driver = driver;
  }
/*
* y el objeto página para una
* página de Inicio podría ser así
*/
  /**
    * Login as valid user
    *
    * @param userName
    * @param password
    * @return HomePage object
    */
  public HomePage loginValidUser(String userName, String password) {
    driver.findElement(usernameBy).sendKeys(userName);
    driver.findElement(passwordBy).sendKeys(password);
    driver.findElement(signinBy).click();
    return new HomePage(driver);
  }
}
/*
* De este modo, la prueba de inicio de sesión utilizaría estos 
* dos objetos página de la siguiente manera:
*/
/***
 * Tests login feature
 */
public class TestLogin {

  @Test
  public void testLogin() {
    SignInPage signInPage = new SignInPage(driver);
    HomePage homePage = signInPage.loginValidUser("userName", "password");
    assertThat(homePage.getMessageText(), is("Hello userName"));
  }

}

/*
* Hay mucha flexibilidad en cómo se pueden diseñar los objetos página, pero hay algunas
* reglas básicas para conseguir la mantenibilidad deseada de su código de prueba.
* Los objetos página en sí mismos nunca deben hacer verificaciones o aseveraciones. Esto es parte de
* su prueba y siempre debe estar dentro del código de la prueba, nunca en un
* objeto página. El objeto página contendrá la representación de la página, y los
* servicios que la página proporciona a través de métodos, pero ningún código
* relacionado con lo que se está probando debe estar dentro del objeto página.
* Hay una única verificación que puede, y debe, estar dentro del objeto página y es verificar
* que la página, y posiblemente los elementos críticos de la página, se cargaron
* correctamente. Esta verificación debe hacerse al instanciar el objeto página.
* En los ejemplos anteriores, tanto el constructor de SignInPage como el de
* HomePage comprueban que la página esperada está disponible y lista para las
* peticiones de la prueba.
* Un objeto página no tiene que representar necesariamente todas las partes de una página en sí.
* Los mismos principios utilizados para los objetos página pueden utilizarse para
* crear "objetos componentes de página" que representan trozos
* discretos de la página y pueden incluirse en los objetos página. Estos objetos
* componentes pueden proporcionar referencias a los elementos dentro de esos
* trozos discretos, y métodos para aprovechar la funcionalidad proporcionada por
* ellos. Incluso se pueden anidar objetos componentes dentro de otros objetos
* componentes para obtener páginas más complejas. Si una página en el AST tiene
* múltiples componentes, o componentes comunes utilizados en todo el sitio (por
* ejemplo, una barra de navegación), entonces puede mejorar la mantenibilidad y
* reducir la duplicación de código.
*/

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I am attaching a screenshot showing the before and after)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2021-09-19 11:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=766) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=766) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=766) it.</sub>

2021-09-20 12:14 UTC, diemol requested changes
@crisgilla, thank you for this PR!

However, could you please directly make the changes on this [file](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/dev/website_and_docs/content/documentation/guidelines/page_object_models.es.md)?

2021-09-28 06:58 UTC, harsha509 commented
Hi @crisgilla,

Did you get a chance to look into the above review comments?

2021-10-05 14:01 UTC, diemol commented
Closing this PR.

2021-10-05 14:01 UTC, closed without merging

2021-10-12 16:28 UTC, crisgilla commented
Hi! Sorry I overlooked this conversation!!I have no problem with changing the file, I just don't know how to work with git and don't know how to do It...

Enviado desde Yahoo Mail con Android 
 
  El mar., oct. 5, 2021 a 16:01, Diego ***@***.***> escribió:   


Closed #766.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.