WIP: change references from seleniumhq.github.io to selenium.dev
SeleniumHQ/seleniumhq.github.io pull request #824
Opened 2021-11-01 20:07 UTC by titusfortner

Getting approval for English version before updating non-English versions.

This also brings up the consideration of how do we flag the non-English versions for being out of date with English versions? Updating the code is easy, but do we just leave the text alone?

2021-12-06 12:00 UTC, diemol requested changes, later dismissed
Maybe add a sentence on top of the page saying "Check the downloads page to see what is the latest version?", since we are using `4.0.0` in the examples.

Also, could you please replace the content of the translated pages and add a notification on top asking for translation contributions?

2021-12-06 12:00 UTC, diemol commented on website_and_docs/content/documentation/getting_started/installing_selenium_libraries.en.md
> +    compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.4.0'
```suggestion
    compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.0.0'
```

2021-12-06 21:53 UTC, titusfortner commented
Made the change, but rebased off of #861, so moving this to draft until that's merged.

2021-12-07 20:45 UTC, diemol approved these changes

2021-12-07 20:52 UTC, merged

2023-06-20 19:39 UTC, Brenocs86 commented on website_and_docs/content/documentation/webdriver/getting_started/install_selenium_library.pt-br.md
>    Setting up the Selenium library for your favourite programming language.
Configurando a biblioteca Selenium para sua linguagem de programção favorita

2023-06-20 19:41 UTC, Brenocs86 commented on website_and_docs/content/documentation/webdriver/getting_started/install_selenium_library.pt-br.md
>    Setting up the Selenium library for your favourite programming language.
translation to portuguese from the "Setting up the Selenium library for your favourite programming language."