Update _index.ko.md
SeleniumHQ/seleniumhq.github.io pull request #829
Opened 2021-11-09 10:24 UTC by sangheon4353

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2021-11-09 10:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=829) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=829) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=829) it.</sub>

2021-11-10 16:43 UTC, diemol requested changes
👋 @sangheon4353, could you please check again step 3 from our [contribution guidelines](https://www.selenium.dev/documentation/about/contributing/#step-3-make-changes)? Line lenghts are exceeding the desired ones, also, relevant words like "Grid" are getting removed.

Also, when using Google Translate, I am getting very similar results as the text presented in this PR. Could you please assure us this translation is "human" made?

2021-11-12 14:16 UTC, sangheon4353 commented
> 👋 @sangheon4353, could you please check again step 3 from our [contribution guidelines](https://www.selenium.dev/documentation/about/contributing/#step-3-make-changes)? Line lenghts are exceeding the desired ones, also, relevant words like "Grid" are getting removed.
> I checked your guidelines and modified that point. Please check again and comment if it isn't fixed. 


> Also, when using Google Translate, I am getting very similar results as the text presented in this PR. Could you please assure us this translation is "human" made?
> In the past, I used this sites to know how to use Selenium and at that moment I used Google translate. But that translation 
was horrible. Each words or sentence can be correct grammatically, but sometimes they bring wrong translation in the context. 
For example, google translates 'Cucumber Library' as '오이', which means real 'cucumber'. Also, lots of conjuctions and 
connective words couldn't do their own work. These mistranslation made us hard to understand, so I am trying to translate
first in translation application, and then I go over each line to understand easily(change connective words, conjunctions, mistran
slation, etc.)
Moreover, there are some pages that already translated in Korean, but those were used by translation, and didn't go over it.
That's why I translate more flexible to make Korean understand easily.

2021-12-03 18:56 UTC, diemol commented
Hi @sangheon4353, thank you for putting this all together. However, after collecting data and understanding better the state of the docs translations, we have decided to hold a few languages (including `ko`) due to their low usage and/or % of content translated. Please read more at https://www.selenium.dev/blog/2021/docs-translations/.

If you are interested in being a volunteer, please reach out to us through https://www.selenium.dev/getinvolved/#translating_site.

2021-12-03 18:56 UTC, closed without merging