Proposal: Prune Translations and Add Official Translator Position to Governance
SeleniumHQ/seleniumhq.github.io pull request #858
Opened 2021-11-24 20:27 UTC by titusfortner

I'm not sure what is needed to update the Governance Doc. Agreement by TLC and/or PLC?

The underlying issue is that trying to reorganize and update the English documents becomes extremely unwieldy when it requires updating aliases, creating new files and marking translation pages potentially out of date for 8 additional languages.

Here's the number of visitors on the landing page for a given translation in the past 2 weeks, and the percent of documentation pages translated:
| language | visitors | translated |
| --------- | ------- | ------- |
| ja | 1,700 | 86% |
| zh-cn | 1,500 | 86% |
| es| 409 |  42% |
| fr | 203 | 31% |
| pt-br | 189 | 87% |
| de | 88 | 65% |
| ko | 79 | 68% |
| nl | 22 | 6% |

### Proposal 1

We archive translations for `nl`, `ko`, `de`, `fr`, and `es`, until such time as we can find a dedicated translator for that language. I'm thinking we archive these to a separate branch so if someone wants to pick up where the old ones left off they will have access to them.

That would leave us with maintaining: `en`, `ja`, `zh-cn`, `pt-br`

### Proposal 2

We create a new role in our governance for dedicated translators for given languages. We recognize them on our website. I'm working on a major reorganization of docs (#843), and I'm planning to update a lot of the docs in the near future, and I'm hoping I can collaborate with the translators when I do this.

@luisfcorreia has agreed to maintain pt-br translations.

@alaahong would you be willing to take responsibility for maintaining `zh-cn` translations? Do you have access to Matrix / IRC / Slack to chat with us, or is GitHub the best way to communicate?

@kzhirata same thing with `ja` translation, would you be interested / willing to take responsibility for those? Would you be able to join our chat room to coordinate?

@boris779 I see you've been doing a lot of work on German translations. We aren't getting a ton of people visiting the German landing page, but if you would like to take responsibility for keeping these pages up to date, we can skip archiving them, and do the work to copy things over in the reorganization. What do you think?

@diemol I don't trust my wording choices on everything in this PR, so please make edits.

2021-11-25 10:45 UTC, kzhirata commented
@titusfortner Thank you for your translation notice. I will be responsible for translating the following PR little by little.
https://github.com/SeleniumHQ/seleniumhq.github.io/pull/843 
And I just joined the slack channel #selenium-docs .

2021-11-25 12:40 UTC, titusfortner commented
@kzhirata that PR is mostly just reorganization, the main content updates will start coming after that. :)

2021-11-26 17:09 UTC, titusfortner commented
Also of potential interest here, I've added a language "Other" for the landing page that contains:

> Is there another translation you'd like to see? We're only supporting translations for which we have 
> a dedicated translator. If you'd like to volunteer to be a translator, read how you can help

2021-11-27 15:47 UTC, alaahong commented
Hi @titusfortner 
It's my honor to take this responsibility,  just joint the slack channel #selenium-docs , other place else need please  let me know. 
Thanks.

2021-12-02 11:08 UTC, diemol requested changes
Aside from the suggestion, 👍 

Thanks, @titusfortner!

2021-12-02 11:08 UTC, diemol commented on website_and_docs/content/project/governance/_index.html
> +      <h4 class="pt-4">Process for becoming a triager</h4>
```suggestion
      <h4 class="pt-4">Process for becoming a translator</h4>
```

2021-12-03 10:35 UTC, diemol approved these changes

2021-12-03 10:43 UTC, merged