Update install_drivers.en.md
SeleniumHQ/seleniumhq.github.io pull request #871
Opened 2021-12-10 05:04 UTC by wmaiouiru

Service input argument doesn't exist in the selenium-python documentation.
https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.chrome.webdriver
The previous documentation doesn't show the import of `Service`.

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2021-12-10 05:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=871) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=871) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=871) it.</sub>

2021-12-11 19:56 UTC, titusfortner approved these changes

2021-12-12 08:19 UTC, diemol requested changes
Can you please update the code snippet in the translated pages as well?

2021-12-12 08:41 UTC, wmaiouiru commented
`1. Driver Management Software` section is not translated to the other languages, unfortunately... 
Trying to add those sections in the other languages is a bit much then I would like to take on...

2021-12-12 09:08 UTC, diemol approved these changes
You are right. I missed that. Thank you!

2021-12-12 09:12 UTC, merged