create shortcode for markdown tabs
SeleniumHQ/seleniumhq.github.io pull request #872
Opened 2021-12-11 04:09 UTC by titusfortner

I'm tempted to put this in draft because it's not the best way to do this, even though it works.

Current docsy theme forces tabs to have highlighting (https://github.com/google/docsy/issues/550)
Would be nice if we could toggle that off on a per-tab basis.

Since I still can't wrap my head around go/hugo enough to do it the right way, I just copied this from the previous docsy implementation when they didn't have automatic highlighting.

I also added padding and a border, but that's about the extent of my design skills.

2021-12-11 19:55 UTC, titusfortner commented
One of the big advantages of using something like this, imo, is that IntelliJ recognizes Ruby comments (`#`) as comments when it's inside 3 ticks, but thinks it is an h1 when it is just inside the tab, so it's much harder to work with the document.

2021-12-13 12:45 UTC, diemol requested changes
This looks nice 
![image](https://user-images.githubusercontent.com/5992658/145814835-d9c47fab-7a41-479e-90ab-efa8b5b7aa22.png)

Is it possible to remove the black border for the tab?

We can merge this, but also, could you please open a PR to docsy? It'd be nice to have this working upstream and then we just use it without having this custom code.

2021-12-23 00:04 UTC, titusfortner commented
I'm converting this to a draft, because I really want us to find a way to create a toggle for this behavior and make a PR to docsy. I don't like having to specify all the tabs in the tabpane with this PR, it just feels clunky.

I added the border because without the `highlight` background, it's really hard to see where the tab content ends. We could do an <hr> instead. I set it to be an `outset` border, which makes it more pronounced at the bottom than the top because that's where it is needed.

2022-01-07 01:41 UTC, titusfortner commented
Closed in favor of #915

2022-01-07 01:41 UTC, closed without merging