Update select_elements.en.md
SeleniumHQ/seleniumhq.github.io pull request #880
Opened 2021-12-13 10:59 UTC by insumanth

Replaced the &lt; and &gt; to < and > in a example for python and ruby.

The &lt; and &gt; are not rendered to < and > symbols as they are formatted as code.
It is displayed as '&lt;select&gt;' in the webpage, so made this changes so it will be displayed as '<select>'.
 
Please add this proposed changes as it may affect people who are reading examples.

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [x] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2021-12-13 11:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=880) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=880) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=880) it.</sub>

2021-12-13 12:12 UTC, diemol requested changes
Could you please change this also in the `select_elements.ja.md`, `select_elements.pt-br.md` and `select_elements.zh-cn.md`?

2021-12-13 12:14 UTC, insumanth commented
Ok. I'll make these changes also

2021-12-13 13:09 UTC, insumanth commented
Hi @diemol, I updated the changes in other mentioned files also.
Please review and merge. Thank you.

2021-12-13 13:34 UTC, diemol commented
Could you please fix the merge conflicts?

2021-12-18 15:20 UTC, harsha509 commented
Hi @insumanth,

Hope you're doing well.

Did you get a chance to look into the above comments?

2021-12-23 03:49 UTC, titusfortner commented
Since I'm the one who made it complicated, I cherry picked/squashed/merged for you: https://github.com/SeleniumHQ/seleniumhq.github.io/commit/c5e7d7dc3ec0de1b25a94ad13d3240ed3795684c

Thanks for your contribution!

2021-12-23 03:49 UTC, closed without merging