implement a toggle for docsy tabpanes so that it doesn't automatically add code
SeleniumHQ/seleniumhq.github.io pull request #915
Opened 2022-01-07 01:40 UTC by titusfortner

This replaces #872 

I figured out how to toggle instead of replace, this is a much easier way to do this. 
@diemol I'm waiting to PR it to Docsy based on your feedback.

You can see examples of everything in the new style guide page I made.

2022-01-07 19:42 UTC, titusfortner commented
Added a new commit to put a GitHub link at the bottom of a tab in auto-code-block mode

2022-01-10 11:00 UTC, diemol requested changes
I think we can merge this, but there seems to be a conflic I would prefer you to fix it so we can merge. Thanks, @titusfortner!

2022-01-10 20:31 UTC, titusfortner commented
Ok, I rebased this, adding the other new content to the new Styles documentation page.
Also slightly better CSS than what I had before

2022-01-10 21:11 UTC, diemol approved these changes

2022-01-10 21:12 UTC, merged