fix move_by_offset example
SeleniumHQ/seleniumhq.github.io pull request #928
Opened 2022-01-14 14:05 UTC by dkg

### Description

`move_by_offset` doesn't have a specific element that it interacts with.

This change cleans up the Python version of the example.

I don't have experience with the non-Python languages, and I don't want to introduce bugs there.
I hope someone else will clean them up.

### Motivation and Context

The existing example is confusing because it refers to things that are irrelevant.

### Types of changes
- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist
- [x] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2022-01-14 14:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=928) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=928) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/seleniumhq.github.io?pullRequest=928) it.</sub>

2022-01-14 14:06 UTC, dkg commented
fwiw, i don't  believe this contribution to be copyright-relevant.  I am not going to sign any CLA, though.

2022-01-16 22:38 UTC, titusfortner commented
The CLA just means that you or your company aren't going to assert ownership / copyright for the line(s) of text/code you write. You are correct that this fix is minor, and we could fix it ourselves under fair use, but for any code to get merged the author needs to sign the CLA.

2022-01-16 22:38 UTC, titusfortner requested changes
The problem is that Python and C# are doing something different from the other languages in this example.
The code is supposed to determine the location of the element from a rect and then move the mouse to the element.
In Python & C# for some reason, the x/y values are hard coded, and we need to update it to get the values dynamically like in the other languages.

2022-01-21 15:20 UTC, dkg commented
ok, well, those changes sound more involved, and might even be copyrightable, so since i'm unlikely to have the cycles to push this CLA through any sort of legal review (and honestly, i'm confused now as to what the CLA entails, see below), i won't make the changes myself.

Even trying to figure out what the CLA says (without running it by general counsel) is more work than i'm capable of doing to get this minor bug fixed.  when i look at https://www.selenium.dev/documentation/about/contributing/, step 7 says:

> Please indicate that you’ve signed the CLA (see Step 7).

i don't know how "see Step 7" *in* step 7 is supposed to do anything but demotivate and confuse me, although i do enjoy a good Joseph Heller novel 😛.

Clicking [the link](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=928) provided by @CLAassistant isn't much better, it just says "Hey, !" unless i enable running javascript from cloudflare, which i'm not about to do in my main browser.  In a different browser profile, where all javascript is promiscuously allowed, it requires me to sign into github to sign the CLA.  but of course i won't run arbitrary javascript in promiscuous mode in a browser that is also signed into a sensitive account (like github).

What does the CLA actually say?  In the promiscuous browser,  [the link](https://cla-assistant.io/SeleniumHQ/seleniumhq.github.io?pullRequest=928) says, apparently in full:

> Software Freedom Conservancy, the non-profit corporate home of the Selenium Project, requests that You sign a Contributor License Agreement ("CLA") regarding any software code and/or documentation You desire to contribute to the Selenium Project ("Contribution").
> 
> By submitting your Contribution to the Selenium Project, You hereby agree to license your Contribution under the Apache License, Version 2.0, and to include the appropriate copyright notice required by the license.

If all this does is ensure that i'm licensing my contribution under Apache license 2.0, then of course i agree to do that.  I already did that by submitting the request here in a project that is explicitly and clearly flagged as a project licensed under Apache 2.0.  But "CLA" typically is used to mean "assign your copyright to the project", which is a much heavier ask than what the text above says.

Moreover, @titusfortner says:

> The CLA just means that you or your company aren't going to assert ownership / copyright for the line(s) of text/code you write.

But if that's the case, then i *cannot* "license [my] Contribution under the Apache License", which would of course require asserting ownership.  So now i don't know what to believe about the CLA, even if i had the cycles to run it by legal counsel.

Overall, this CLA process has interfered with and distracted me from the task at hand, of actually improving the documentation.  pretty frustrating and disappointing!  I write this in all sympathy, as someone who appreciates Selenium, likes to contribute back where possible, and as a long-time supporter of the Software Freedom Conservancy.

2022-01-21 21:33 UTC, titusfortner commented
Sorry for the extra hassle, but I appreciate you taking the time to make the distinction you have. 

I agree this is unclear, and we need to talk to Software Freedom Conservancy about what the actual distinction is.

2022-01-22 01:33 UTC, anarcat commented
i find it sadly hilarious that a 4 line patch to *remove* code requires about 200 lines of discussion.

CLAs are really a barrier to collaboration. i understand why you might need them, but i think you should also exercise judgement in applying it. this is a clear example of how something simple becomes needlessly complicated.

2022-01-22 02:18 UTC, titusfortner commented
Except the right fix is not to remove these lines, but to fix the implementation as I mentioned earlier, so the conversation about the CLA is independent of your current proposal. 

There are lots of barriers to contributing to open source code. Signing a CLA as an individual contributor not planning future legal action against the project doesn't really come close to being one of them.

I'm still planning to check about whether the CLA and our Notice file are correctly in agreement, but it's more academic than a limiting issue.

Since you don't appear to be interested in our contribution requirements or in addressing the underlying problem you identified, I'm closing the PR and will raise a separate issue.

2022-01-22 02:18 UTC, closed without merging