add a shortcode for linking to github when disableCodeBlock=true
SeleniumHQ/seleniumhq.github.io pull request #935
Opened 2022-01-20 17:46 UTC by titusfortner

Feedback that linking to Github examples wasn't clear when code block is disabled in a tab, so I created a shortcode for it.

2022-01-20 18:30 UTC, harsha509 requested changes

2022-01-20 18:30 UTC, harsha509 commented on website_and_docs/content/documentation/about/style.en.md
> +{{< tab header="Link" github="SeleniumHQ/seleniumhq.github.io/tree/dev/examples/java/src/test/java/dev/selenium/getting_started/FirstScriptTest.java#L16-L35" >}} /
can we remove '/'. I assume this is by mistake!

2022-01-25 17:25 UTC, titusfortner commented on website_and_docs/content/documentation/about/style.en.md
> +{{< tab header="Link" github="SeleniumHQ/seleniumhq.github.io/tree/dev/examples/java/src/test/java/dev/selenium/getting_started/FirstScriptTest.java#L16-L35" >}} /
```suggestion
{{< tab header="Link" github="SeleniumHQ/seleniumhq.github.io/tree/dev/examples/java/src/test/java/dev/selenium/getting_started/FirstScriptTest.java#L16-L35" >}}
```

2022-01-30 15:56 UTC, harsha509 approved these changes

2022-01-30 15:57 UTC, merged