Adding info for IsDisplayed() selenium method
SeleniumHQ/seleniumhq.github.io pull request #958
Opened 2022-02-17 20:22 UTC by MartinoHead

The information about IsDisplayed() method is missing. Examples are also missing. I am adding basic description and later will add examples.

**Thanks for contributing to the Selenium site and documentation!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Change to the site (I have double-checked the Netlify deployment, and my changes look good)
- [ ] Code example added (and I also added the example to all translated languages)
- [ ] Improved translation
- [ ] Added new translation (and I also added a notice to each document missing translation)

### Checklist

- [ ] I have read the [**contributing**](https://selenium.dev/documentation/en/contributing/) document.
- [ ] I have used [hugo](https://gohugo.io/) to render the site/docs locally and I am sure it works.

2022-02-17 21:21 UTC, diemol requested changes
Could you please add this information to the other `information.*.md` files?

2022-02-17 21:21 UTC, diemol commented on website_and_docs/content/documentation/webdriver/elements/information.en.md
> +The isDisplayed method in Selenium verifies if a certain element is present and displayed. If the element is displayed, then the value returned is true. If not, then the value returned is false.
Please use max 100 chars per line.

2022-02-18 08:36 UTC, MartinoHead commented
> Could you please add this information to the other `information.*.md` files?

I don't have this description in other languages. Should i just use google traslator?

2022-02-18 08:54 UTC, diemol commented
> > Could you please add this information to the other `information.*.md` files?
> 
> I don't have this description in other languages. Should i just use google traslator?

There is no need to translate, the English content is fine. One of the translators will have a look at it.

2022-03-02 15:49 UTC, harsha509 commented
Hi @MartinoHead,

Thank you for taking time and raising the PR.

I was not aware of this PR but and replaced this PR with commit https://github.com/SeleniumHQ/seleniumhq.github.io/commit/9cfe79bcda83e4c7d84c884b4b5a990c8159a4c3 !

Thanks,
Harsha

2022-03-02 15:50 UTC, closed without merging